"""Iteration 9 expansion: more civilizations, diaspora communities, places (with detail pages)."""

EXTRA_CIVILIZATIONS = [
    {
        "id": "ghana-empire",
        "name": "Ghana Empire (Wagadu)",
        "region": "West Africa",
        "modern_locations": ["Mauritania", "Mali", "Senegal"],
        "coords": [15.75, -8.50],
        "era_start": 300,
        "era_end": 1240,
        "summary": "The earliest of the great West African Sahelian empires, known to Arab geographers as 'the land of gold' — predecessor of Mali and Songhai.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Sacred kingship of the Ghana (war-king title that gave the empire its later name); twin-city capital of Koumbi Saleh with a Muslim merchant quarter and a royal pagan quarter.",
        "economy_and_trade": "Gold from Bambuk and Bure exchanged at fixed rates for Saharan salt; the king reportedly held a monopoly on gold nuggets while permitting subjects to trade dust.",
        "science_and_knowledge": "Bilingual administration through Soninke and Arabic from at least the 9th century; preserved in the writings of al-Bakri (1068).",
        "art_and_culture": "Soninke oral tradition (Dinga Cisse founder epic), elaborate court regalia described by Arab travelers.",
        "key_figures": [
            {"name": "Tunka Manin", "role": "King visited by Arab geographer al-Bakri (r. c. 1063–1068)"},
            {"name": "Sumanguru Kanté", "role": "Sosso king who briefly succeeded Ghana before being defeated by Sundiata"},
        ],
        "timeline": [
            {"year": 800, "event": "Earliest secure Arabic references to the empire of Ghana."},
            {"year": 1068, "event": "al-Bakri describes Koumbi Saleh in his 'Kitab al-Masalik'."},
            {"year": 1240, "event": "The Mali empire under Sundiata absorbs the remnant Ghana territory."},
        ],
        "sources": ["al-Bakri, 'Kitab al-Masalik wa-l-Mamalik' (1068)", "Nehemia Levtzion, 'Ancient Ghana and Mali' (1973)"],
    },
    {
        "id": "carthage",
        "name": "Carthage",
        "region": "North Africa",
        "modern_locations": ["Tunisia", "Libya", "Algeria", "Spain", "Sardinia", "Sicily"],
        "coords": [36.8528, 10.3236],
        "era_start": -814,
        "era_end": -146,
        "summary": "Phoenician colony founded by Tyre that became the dominant Mediterranean maritime empire of the Western Mediterranean, famously contesting Rome in the three Punic Wars.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Republic governed by two annually elected suffetes and a senate; mercenary armies under noble commanders (the Barcid family).",
        "economy_and_trade": "Tin, silver, ivory, slaves; circumnavigation of Africa traditionally attributed to Hanno the Navigator (c. 500 BCE).",
        "science_and_knowledge": "Mago of Carthage wrote a 28-book agronomic treatise so important Rome ordered its translation after the city's destruction.",
        "art_and_culture": "Punic temples, the 'tophet' precinct, distinctive stelae, and a Phoenician script preserving North African Semitic literature.",
        "key_figures": [
            {"name": "Dido (Elissa)", "role": "Founder according to tradition (c. 814 BCE)"},
            {"name": "Hanno the Navigator", "role": "Explorer of the West African coast (c. 500 BCE)"},
            {"name": "Hannibal Barca", "role": "General who crossed the Alps with war elephants (218 BCE)"},
        ],
        "timeline": [
            {"year": -814, "event": "Traditional founding by Tyrian settlers."},
            {"year": -264, "event": "First Punic War with Rome begins."},
            {"year": -218, "event": "Hannibal crosses the Alps."},
            {"year": -146, "event": "Roman destruction; the site is razed and ritually cursed."},
        ],
        "sources": ["Polybius, Histories", "Richard Miles, 'Carthage Must Be Destroyed' (2010)"],
    },
    {
        "id": "buganda",
        "name": "Kingdom of Buganda",
        "region": "East Africa",
        "modern_locations": ["Uganda"],
        "coords": [0.3476, 32.5825],
        "era_start": 1300,
        "era_end": 1894,
        "summary": "Centralized Bantu kingdom on the northern shore of Lake Victoria, distinguished by a powerful administrative class and a navy of war-canoes that dominated regional commerce.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Hereditary monarchy of the Kabaka, balanced by appointed chiefs (bakungu) drawn from commoners rather than royal lineages.",
        "economy_and_trade": "Plantain agriculture, cotton bark-cloth, ivory; integrated into the East African coastal trade from the 19th century.",
        "science_and_knowledge": "Sophisticated war canoe construction, the Luganda language with rich praise-poetry tradition.",
        "art_and_culture": "Royal regalia, the kasubi tombs of the Kabakas (UNESCO World Heritage), drum traditions tied to kingship.",
        "key_figures": [
            {"name": "Kintu", "role": "Mythical founder-king"},
            {"name": "Mutesa I", "role": "Kabaka who received explorer John Hanning Speke in 1862 (r. 1856–1884)"},
            {"name": "Mwanga II", "role": "Last fully sovereign Kabaka (r. 1884–1897)"},
        ],
        "timeline": [
            {"year": 1862, "event": "Speke is received at Mutesa's court."},
            {"year": 1885, "event": "Buganda Martyrs executed under Mwanga II — both Christian and traditional sources document the event."},
            {"year": 1894, "event": "British protectorate declared over Buganda."},
        ],
        "sources": ["John Hanning Speke, 'Journal of the Discovery of the Source of the Nile' (1863)", "Christopher Wrigley, 'Kingship and State' (1996)"],
    },
    {
        "id": "sokoto",
        "name": "Sokoto Caliphate",
        "region": "West Africa",
        "modern_locations": ["Nigeria", "Niger", "Cameroon"],
        "coords": [13.0059, 5.2476],
        "era_start": 1804,
        "era_end": 1903,
        "summary": "One of the largest African states of the 19th century — a Fulani-led Islamic caliphate founded by Usman dan Fodio that incorporated the Hausa city-states under a single political-religious authority.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Caliphate divided into emirates each ruled by an emir appointed by the Sultan in Sokoto; advisory council of scholars.",
        "economy_and_trade": "Agricultural surplus from the Hausa plains, leather and textile crafts, trans-Saharan trade; large-scale plantation systems.",
        "science_and_knowledge": "Major center of Islamic scholarship; Usman dan Fodio, his brother Abdullahi, and his daughter Nana Asmaʼu produced hundreds of works in Arabic, Hausa, and Fulfulde.",
        "art_and_culture": "Hausa-Fulani architecture, embroidered babbar riga, Ajami literary tradition (Hausa/Fulfulde in Arabic script).",
        "key_figures": [
            {"name": "Usman dan Fodio", "role": "Founder, scholar, Sultan (r. 1804–1817)"},
            {"name": "Nana Asmaʼu", "role": "Scholar, poet, women's educator (1793–1864)"},
            {"name": "Muhammadu Bello", "role": "First Sultan after Usman (r. 1817–1837)"},
        ],
        "timeline": [
            {"year": 1804, "event": "Usman dan Fodio's jihad begins."},
            {"year": 1809, "event": "Sokoto founded as capital."},
            {"year": 1903, "event": "British forces under Lugard defeat Sokoto; the Caliphate falls."},
        ],
        "sources": ["Murray Last, 'The Sokoto Caliphate' (1967)", "Jean Boyd, 'The Caliph's Sister: Nana Asmaʼu' (1989)"],
    },
]

EXTRA_DIASPORA = [
    {
        "id": "afro-venezuelan", "name": "Afro-Venezuelan", "country": "Venezuela", "country_iso2": "VE", "status": "documented", "region": "South America",
        "coords": [10.6090, -66.9156], "era_start": 1520, "era_end": 2025,
        "summary": "Venezuela received an estimated 100,000–120,000 enslaved Africans, concentrated on coastal cacao estates from Barlovento to the Yaracuy valley. Today the community is the cultural heart of coastal Venezuela.",
        "origin_routes": ["West-Central Africa (Kongo, Angola)", "Bight of Benin"],
        "ethnicities": ["Loango and Kongo heritage on the Barlovento coast", "Cumbe (free Black town) descendants"],
        "languages": ["Venezuelan Spanish (with Bantu and Yoruba lexical residue)"],
        "religions": ["Catholicism, often syncretized with African elements (especially in San Juan and San Benito festivities)"],
        "culture": "Drum traditions of Barlovento (tambor mina, curbata, fulía), the Diablos Danzantes of Yare (UNESCO Intangible Heritage 2012), San Juan festivals.",
        "story": "The 1795 Coro insurrection led by José Leonardo Chirino, a free zambo (Afro-Indigenous), was an early demand for the abolition of slavery in Spanish America. Free Black militias played a decisive role in the wars of independence under Bolívar.",
        "modern": "Constitutional recognition of Afro-Venezuelans in the 1999 constitution; visible cultural presence in music (Oscar D'León), sport, and politics.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Federico Brito Figueroa, 'El problema tierra y esclavos en la historia de Venezuela' (1973)"],
    },
    {
        "id": "afro-dominican", "name": "Afro-Dominican", "country": "Dominican Republic", "country_iso2": "DO", "status": "documented", "region": "Caribbean",
        "coords": [18.4861, -69.9312], "era_start": 1502, "era_end": 2025,
        "summary": "Hispaniola was the first major site of enslaved African labor in the Americas. Today over 70% of Dominicans are of African descent.",
        "origin_routes": ["West-Central Africa", "Bight of Benin", "Senegambia (very early)"],
        "ethnicities": ["Cocolos (English-speaking Afro-Caribbean immigrants from St. Kitts, Nevis, Tortola who came as sugar workers from 1880s)", "Cimarrones of San Lorenzo de los Mina"],
        "languages": ["Dominican Spanish", "Samaná English (Afro-American Samaná community, 19th-c. settlers)"],
        "religions": ["Catholicism", "Dominican Vudú (Las 21 Divisiones)", "Gagá processions"],
        "culture": "Merengue and bachata; the Carnival traditions of Santiago and La Vega; the music of Juan Luis Guerra; literature of Junot Díaz and Julia Alvarez (Dominican-American).",
        "story": "Enriquillo, a Taíno cacique baptized by Spanish friars, led a 14-year mountain rebellion (1519–1533) that included Africans and is considered the first sustained Black-Indigenous resistance in the Americas. Sebastián Lemba led a maroon uprising in 1547 that eluded Spanish forces for 15 years.",
        "modern": "Black identity remains politically complex due to the long shadow of the 1937 anti-Haitian Parsley Massacre; an increasingly vocal Afro-Dominican cultural movement since 2000.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Frank Moya Pons, 'The Dominican Republic: A National History' (1995)"],
    },
    {
        "id": "afro-canadian", "name": "Afro-Canadian", "country": "Canada", "country_iso2": "CA", "status": "documented", "region": "North America",
        "coords": [43.6532, -79.3832], "era_start": 1605, "era_end": 2025,
        "summary": "Africans were present in Canada from 1605 (Mathieu da Costa, the first known person of African origin). Major waves include Black Loyalists (1783), Underground Railroad migrants (1800s), and Caribbean and African migration since the 1960s. Today over 1.5 million Canadians identify as Black.",
        "origin_routes": ["Underground Railroad from the United States (1800s)", "Black Loyalists from the U.S. (after 1783)", "Caribbean migration (Jamaica, Trinidad, Haiti) from 1960s", "Direct African migration (Nigeria, Ghana, Somalia, DRC)"],
        "ethnicities": ["Black Nova Scotians (descendants of Black Loyalists and Jamaican Maroons relocated in 1796)", "Caribbean Canadians", "Continental African Canadians"],
        "languages": ["Canadian English", "Canadian French (especially in Montreal Haitian community)", "Heritage languages"],
        "religions": ["Black Baptist churches (especially in Nova Scotia)", "Catholicism (Haitian and Francophone African)", "Islam (Somali community)"],
        "culture": "The Toronto Caribbean Carnival (Caribana, 1967–), the music of Drake and the Weeknd, writers Dionne Brand and Esi Edugyan, the long activist tradition from Viola Desmond (whose bus protest predated Rosa Parks by 9 years) to current MPs.",
        "story": "Africville, a historic Black community in Halifax founded c. 1848, was destroyed by the city between 1964 and 1970. The Halifax government apologized in 2010. The Underground Railroad ended in southern Ontario towns including Buxton and Chatham, where descendants still live.",
        "modern": "Viola Desmond appears on the Canadian $10 note (since 2018) — the first non-royal woman on Canadian currency.",
        "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Robin Winks, 'The Blacks in Canada' (1971)", "Afua Cooper, 'The Hanging of Angélique' (2006)"],
    },
    {
        "id": "afro-ecuadorian", "name": "Afro-Ecuadorian", "country": "Ecuador", "country_iso2": "EC", "status": "documented", "region": "South America",
        "coords": [0.9683, -79.6517], "era_start": 1553, "era_end": 2025,
        "summary": "Concentrated in the northwest province of Esmeraldas and the Chota-Mira valley, Afro-Ecuadorians trace their origins partly to a 1553 shipwreck whose African survivors founded the maroon Republic of Zambos.",
        "origin_routes": ["Shipwreck survivors (1553)", "Colonial-era slave trade to coastal Ecuador and the Chota highland sugar valley"],
        "ethnicities": ["Esmeraldas Black community", "Chota-Mira Valley Afro-Ecuadorians"],
        "languages": ["Ecuadorian Spanish (with documented Bantu lexical residue)"],
        "religions": ["Catholicism with strong saints devotion and arrullo processions"],
        "culture": "Marimba esmeraldeña (UNESCO Intangible Heritage 2015, shared with Colombia), bomba del Chota, décima poetry, the writings of Adalberto Ortiz and Antonio Preciado.",
        "story": "Survivors of a 1553 slave-ship wreck under leader Antón established the Republic of Zambos, which Spain never conquered — by 1599 it was officially recognized through the famous 'Mulattoes of Esmeraldas' portrait commissioned by judge Juan del Barrio Sepúlveda and now in the Museo de América in Madrid.",
        "modern": "The 2008 Constitution recognized Afro-Ecuadorians as a distinct nationality; the National Council for the Equality of Peoples and Nationalities monitors policy.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Norman Whitten, 'Black Frontiersmen' (1974)", "Sherwin Bryant, 'Rivers of Gold, Lives of Bondage' (2014)"],
    },
    {
        "id": "afro-italian", "name": "Afro-Italian", "country": "Italy", "country_iso2": "IT", "status": "documented", "region": "Europe",
        "coords": [41.9028, 12.4964], "era_start": 1900, "era_end": 2025,
        "summary": "A young diaspora rooted in Italian colonial history (Eritrea, Somalia, Libya, Ethiopia) and reinforced by major migrations from West and North Africa since the 1990s.",
        "origin_routes": ["Italian colonial-era migration from Eritrea, Somalia, Libya, Ethiopia", "West African migration (Nigeria, Senegal, Ghana, Côte d'Ivoire) from 1980s", "Mediterranean refugee crossings"],
        "ethnicities": ["Eritrean-Italians and Somali-Italians (often Italian-speaking from colonial schools)", "Senegalese, Nigerian, Ghanaian Italians"],
        "languages": ["Italian", "heritage languages (Tigrinya, Somali, Wolof, Igbo, etc.)"],
        "religions": ["Catholicism", "Islam (large Senegalese Mouride community)", "Orthodox Christianity (Eritrean and Ethiopian)"],
        "culture": "Italo-Senegalese music (Saint-Levy, Tommy Kuti), writers Igiaba Scego and Pap Khouma, the Black Italian feminist movement (Razzismo Brutta Storia, BHM Italy).",
        "story": "Italy never reckoned formally with its colonial history (Libya 1911–1947, Ethiopia 1936–41, Eritrea 1890–1947, Somalia 1889–1960). The 'jus soli' citizenship debate, with hundreds of thousands of Italian-born children of African parents still denied citizenship until adulthood, has driven a generation of Black Italian activism.",
        "modern": "Cécile Kyenge became Italy's first Black cabinet minister in 2013. Mario Balotelli, Paola Egonu (volleyball), and Khaby Lame (most-followed TikTok user) are global Afro-Italian icons.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Pap Khouma, 'I Was an Elephant Salesman' (1990)", "Heather Merrill, 'Black Spaces' (2018)"],
    },
    {
        "id": "afro-iranian", "name": "Afro-Iranian / Zanj", "country": "Iran", "country_iso2": "IR", "status": "documented", "region": "Middle East",
        "coords": [29.0982, 50.8385], "era_start": 800, "era_end": 2025,
        "summary": "Communities of Afro-Iranians (Siyah-pust) trace ancestry to enslaved East Africans brought across the Indian Ocean to work the date palm groves and ports of Bushehr, Bandar Abbas, and Hormozgan.",
        "origin_routes": ["East African coast via Indian Ocean", "Ethiopia and Zanzibar"],
        "ethnicities": ["Afro-Iranians of the Persian Gulf coast"],
        "languages": ["Persian (with Swahili-derived loanwords in southern coastal dialects)"],
        "religions": ["Twelver Shia Islam", "Folk practices including zār spirit-possession ceremonies of clearly East African origin"],
        "culture": "Zār ritual music and the nayanban (East African bagpipe), distinctive Hormozgan music with Swahili rhythmic structure; the documentary 'Cinema Travellers' and the photography of Mahdi Ehsaei.",
        "story": "The 869–883 Zanj Rebellion in southern Iraq was an uprising of enslaved East Africans against the Abbasid Caliphate — among the largest slave revolts in pre-modern history. Centuries of continued trafficking populated the Iranian coast.",
        "modern": "Slavery was formally abolished in Iran in 1929. The Afro-Iranian community remains underrepresented in national media but is increasingly documented by Iranian photographers and scholars.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Behnaz Mirzai, 'A History of Slavery and Emancipation in Iran' (2017)", "Mahdi Ehsaei, 'Afro-Iran' (2015, photo book)"],
    },
]

# Extended PLACES — each is now eligible for a /place/:id deep-dive page
EXTRA_PLACES = [
    {"id": "rova", "name": "Rova of Antananarivo", "type": "site", "coords": [-18.9261, 47.5325], "era": "17th–19th c.",
     "blurb": "Royal palace complex of the Kingdom of Madagascar atop the hill of Antananarivo, partially destroyed by fire in 1995 and now under reconstruction.",
     "story": "The Rova housed the tombs of the Merina sovereigns from Andrianampoinimerina through Ranavalona III. Queen Ranavalona I commissioned the great wooden palace Manjakamiadana, later encased in stone by the Frenchman Jean Laborde. After Madagascar's annexation in 1896, the site became a contested symbol of sovereignty.",
     "sources": ["UNESCO Tentative List (Madagascar)"]},
    {"id": "sankore", "name": "Sankoré Madrasa", "type": "site", "coords": [16.7741, -2.9989], "era": "14th–16th c.",
     "blurb": "Center of Islamic learning in Timbuktu, said at its peak to have hosted 25,000 students drawn from across the Sahel and North Africa.",
     "story": "Founded in the 14th century by a wealthy Mandé woman, Sankoré was one of three centers of higher learning in Timbuktu (with Djinguereber and Sidi Yahya) that constituted what some scholars call the University of Timbuktu. The Timbuktu Manuscripts — surviving documents on astronomy, jurisprudence, mathematics, and medicine — testify to its scholarly output.",
     "sources": ["UNESCO Timbuktu inscription"]},
    {"id": "lake-kivu", "name": "Bigo bya Mugenyi (Bigo Earthworks)", "type": "site", "coords": [-0.40, 31.36], "era": "13th–16th c.",
     "blurb": "Vast earthwork complex in present-day western Uganda, often associated with the Bachwezi 'mythical' rulers who became the foundational lore of Uganda's interlacustrine kingdoms.",
     "story": "More than 10 km of ditches and ramparts enclose what may be a royal capital. Archaeology since the 1960s has confirmed substantial Iron Age occupation linked to the Bunyoro-Kitara tradition.",
     "sources": ["Peter Robertshaw, 'The Origins of the State in East Africa' (1994)"]},
    {"id": "fort-jesus", "name": "Fort Jesus, Mombasa", "type": "site", "coords": [-4.0625, 39.6798], "era": "1593 — present",
     "blurb": "Portuguese fortress at the entrance of Mombasa harbor that changed hands nine times between Portuguese, Omanis, and the British — UNESCO World Heritage.",
     "story": "Designed by Italian architect Giovanni Battista Cairati for the Portuguese in 1593. After the great Omani siege (1696–98) Mombasa passed under Omani control, becoming a node of the Swahili-Omani trade in cloves, ivory, and slaves.",
     "sources": ["UNESCO World Heritage (Fort Jesus)"]},
    {"id": "axum-stelae", "name": "Axum Stelae Field", "type": "site", "coords": [14.1271, 38.7245], "era": "1st–4th c. CE",
     "blurb": "Field of giant carved monoliths in northern Ethiopia — the tallest single stones ever quarried and erected by any civilization.",
     "story": "Stele 1 (now collapsed) was 33 metres tall — taller than any Egyptian obelisk. Stele 2, looted by Mussolini's Italy in 1937, was returned to Ethiopia in 2005 in three sections after a decades-long campaign.",
     "sources": ["UNESCO World Heritage (Aksum)"]},
    {"id": "old-cairo", "name": "Fustat (Old Cairo)", "type": "city", "coords": [30.0064, 31.2333], "era": "641 — present",
     "blurb": "Egypt's first Islamic capital and one of the densest commercial centers of the medieval world; the Geniza of its Ben Ezra synagogue is the richest pre-modern document archive in existence.",
     "story": "Founded after Amr ibn al-As's conquest of Egypt in 641. By the 11th c. Fustat had multi-story housing and piped water on a scale unmatched in contemporary Europe. The Cairo Geniza fragments — 400,000 manuscript pieces — reshaped what we know of Mediterranean trade.",
     "sources": ["S. D. Goitein, 'A Mediterranean Society' (1967–1993, 6 vols.)"]},
    {"id": "robben-island", "name": "Robben Island", "type": "site", "coords": [-33.8067, 18.3675], "era": "17th c. — present",
     "blurb": "Island off Cape Town used by the Dutch, British, and apartheid South African state as a place of exile and imprisonment; Nelson Mandela spent 18 years here.",
     "story": "Robben Island held political prisoners from the 17th-century anti-Dutch resistance through the 20th-century anti-apartheid struggle. Mandela's cell B is preserved as part of the now UNESCO-listed museum.",
     "sources": ["UNESCO World Heritage (Robben Island)"]},
    {"id": "lalibela2-extra", "name": "Adwa Battlefield", "type": "site", "coords": [14.1667, 38.9000], "era": "1 March 1896",
     "blurb": "Site of the decisive Ethiopian victory over invading Italian forces — the only major battle in which an African state defeated a European colonial army in the imperial era.",
     "story": "Emperor Menelik II and Empress Taytu Betul commanded over 100,000 Ethiopian troops armed with modern rifles imported through diplomatic maneuver. Italian commander Oreste Baratieri's force of ~18,000 was routed with roughly 7,000 killed and 1,500 captured.",
     "sources": ["Raymond Jonas, 'The Battle of Adwa' (2011)"]},
]
