"""Extended content: diaspora communities, heritage places, lineage journey, cultural fusions."""

# ---------- DIASPORA COMMUNITIES ----------
# Each: origin routes, ethnicities, languages, religions, cultural markers, modern reality, sources
DIASPORA_COMMUNITIES = [
    {
        "id": "afro-brazilian",
        "name": "Afro-Brazilian",
        "country": "Brazil", "country_iso2": "BR", "status": "documented",
        "region": "South America",
        "coords": [-12.9714, -38.5014],  # Salvador da Bahia
        "era_start": 1538,
        "era_end": 2025,
        "summary": "Brazil received roughly 4.8 million enslaved Africans — by far the largest national destination of the transatlantic trade. Today over half of Brazilians identify as Black or pardo, the highest in the Americas.",
        "origin_routes": ["West-Central Africa (Kongo, Angola, Benguela)", "Bight of Benin (Yoruba, Ewe, Fon)", "Mozambique"],
        "ethnicities": ["Yoruba (Nagô)", "Bantu (Kongo, Angola, Benguela)", "Fon/Ewe (Jeje)", "Hausa", "Malê (Muslim West Africans)"],
        "languages": ["Brazilian Portuguese (with Bantu and Yoruba loanwords: caçula, dendê, axé)", "Yoruba liturgical language in Candomblé"],
        "religions": ["Catholicism", "Candomblé", "Umbanda", "Evangelical Protestantism"],
        "culture": "Capoeira (martial art / dance), samba, axé, MPB, feijoada, acarajé, Carnival of Salvador and Rio, Afro-Brazilian visual art and the literary tradition of Machado de Assis to Conceição Evaristo.",
        "story": "Salvador da Bahia was the colonial capital from 1549 to 1763 and the principal port of entry. The quilombo of Palmares in Alagoas, led by Ganga Zumba and Zumbi, resisted Portuguese forces for almost a century (c. 1605–1694). The Malê Revolt of 1834 in Bahia, organized by Muslim Hausa and Yoruba, was the largest urban slave revolt in the Americas. Brazil was the last country in the Western Hemisphere to abolish slavery, in 1888.",
        "modern": "Movimento Negro Unificado (1978–), affirmative-action quotas in federal universities (2012–), the rise of Afro-Brazilian intellectuals (Lélia Gonzalez, Sueli Carneiro, Djamila Ribeiro).",
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Slavevoyages.org", "IBGE 2022 census", "João José Reis, 'Slave Rebellion in Brazil' (1993)"],
    },
    {
        "id": "african-american",
        "name": "African American",
        "country": "United States", "country_iso2": "US", "status": "documented",
        "region": "North America",
        "coords": [32.7765, -79.9311],  # Charleston
        "era_start": 1619,
        "era_end": 2025,
        "summary": "Roughly 388,000 Africans were brought directly to what is now the United States, with descendants today numbering about 47 million — the cultural engine of much of global popular music.",
        "origin_routes": ["Senegambia (Wolof, Mande, Fula)", "Sierra Leone / Windward Coast", "Gold Coast", "Bight of Biafra (Igbo)", "West-Central Africa"],
        "ethnicities": ["Gullah/Geechee descendants of Sierra Leone rice-coast captives", "Igbo, Kongo, Wolof, Mandinka heritage lines"],
        "languages": ["African American English / AAVE", "Gullah creole (Sea Islands)", "Louisiana Creole"],
        "religions": ["Black Protestantism (AME, Baptist, COGIC)", "Islam (Nation of Islam, Sunni revival from 1970s)", "Hoodoo folk practice"],
        "culture": "Spirituals → gospel → blues → jazz → R&B → soul → funk → hip-hop. Harlem Renaissance literature (Hughes, Hurston, Larsen). The Black church as the organizing institution of the Civil Rights Movement.",
        "story": "The first documented Africans arrived at Point Comfort, Virginia in 1619 aboard the privateer 'White Lion'. Cotton, tobacco, and rice plantations of the South were built on Black labor. The Great Migration (1910–1970) moved roughly 6 million African Americans from the rural South to Northern, Midwestern, and Western cities — remaking American music, politics, and urban life.",
        "modern": "Civil Rights Act (1964), Voting Rights Act (1965), Obama presidency (2009–2017), Black Lives Matter (2013–), Juneteenth as federal holiday (2021).",
        "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Slavevoyages.org", "Isabel Wilkerson, 'The Warmth of Other Suns' (2010)", "Henry Louis Gates Jr., 'Stony the Road' (2019)"],
    },
    {
        "id": "afro-caribbean",
        "name": "Afro-Caribbean (Jamaica & Anglophone)",
        "country": "Jamaica, Trinidad, Barbados, Guyana",
        "scope": "regional", "status": "documented",
        "region": "Caribbean",
        "coords": [18.1096, -77.2975],
        "era_start": 1655,
        "era_end": 2025,
        "summary": "The English-speaking Caribbean received about 2.3 million Africans, producing sugar islands whose descendants reshaped global music (reggae, calypso, soca) and 20th-century political thought.",
        "origin_routes": ["Gold Coast (Akan)", "Bight of Biafra (Igbo)", "West-Central Africa (Kongo)"],
        "ethnicities": ["Akan (Coromantee) heritage strong in Jamaica", "Igbo heritage strong in Barbados"],
        "languages": ["Jamaican Patois (Creole English with Twi/Akan grammar)", "Trinidadian Creole", "Bajan", "Guyanese Creolese"],
        "religions": ["Christianity (Anglican, Baptist, Methodist)", "Rastafari (1930s, Jamaica)", "Obeah / Myal folk practice", "Spiritual Baptist (Trinidad)"],
        "culture": "Reggae, ska, dancehall, calypso, soca, dub poetry (Mutabaruka, Linton Kwesi Johnson), Carnival traditions, jerk cooking, the global Pan-African intellectual tradition of Marcus Garvey, C.L.R. James, Frantz Fanon, Stuart Hall.",
        "story": "Maroon societies in Jamaica's Cockpit Country and Suriname's interior negotiated treaties with the British and Dutch as early as 1739. The Haitian Revolution (1791–1804), led by Toussaint Louverture and Jean-Jacques Dessalines, founded the second independent republic in the Americas and the first to abolish slavery outright. Jamaican independence came in 1962.",
        "modern": "Bob Marley as global ambassador of reggae and Rastafari; Caribbean diasporas in London, Toronto, and New York; reparations advocacy through CARICOM (2013–).",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Slavevoyages.org", "C.L.R. James, 'The Black Jacobins' (1938)", "Stuart Hall, 'Familiar Stranger' (2017)"],
    },
    {
        "id": "afro-cuban",
        "name": "Afro-Cuban",
        "country": "Cuba", "country_iso2": "CU", "status": "documented",
        "region": "Caribbean",
        "coords": [23.1136, -82.3666],  # Havana
        "era_start": 1526,
        "era_end": 2025,
        "summary": "Cuba received roughly 800,000 Africans, with importation continuing well into the 1860s. The late, concentrated arrivals — many from Yoruba and Kongo lands — preserved African religion and rhythm with unusual clarity.",
        "origin_routes": ["Bight of Benin (Yoruba)", "West-Central Africa (Kongo)", "Sierra Leone (in late period)"],
        "ethnicities": ["Lucumí (Yoruba)", "Congo / Bantu", "Carabalí (Cross River region)"],
        "languages": ["Cuban Spanish", "Lucumí (liturgical Yoruba)", "Bozal Spanish (historical pidgin)"],
        "religions": ["Catholicism", "Santería / Regla de Ocha (Yoruba orisha tradition)", "Palo Mayombe (Kongo-derived)", "Abakuá secret society (Cross River origin)"],
        "culture": "Rumba (UNESCO Intangible Heritage), son cubano (foundation of salsa), mambo, batá drums, Afro-Cuban jazz from Chano Pozo to Arturo Sandoval. Writers Nicolás Guillén and Nancy Morejón.",
        "story": "The Aponte Conspiracy of 1812, led by free Black carpenter José Antonio Aponte, anticipated emancipation by half a century. The sugar boom of the 19th century intensified African importation. The Cuban Wars of Independence (1868–1898) saw mass participation by Black Cubans, with Antonio Maceo (the 'Bronze Titan') as their most celebrated general.",
        "modern": "Cuban Revolution (1959) abolished legal segregation; Afro-Cuban art (Wifredo Lam, Belkis Ayón) gained global recognition; renewed dialogue on race since the 2010s.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Slavevoyages.org", "Ada Ferrer, 'Cuba: An American History' (2021)", "Fernando Ortiz, 'Cuban Counterpoint' (1940)"],
    },
    {
        "id": "afro-haitian",
        "name": "Haitian",
        "country": "Haiti", "country_iso2": "HT", "status": "documented",
        "region": "Caribbean",
        "coords": [18.5944, -72.3074],  # Port-au-Prince
        "era_start": 1697,
        "era_end": 2025,
        "summary": "French Saint-Domingue was the most profitable colony in the world before its enslaved population overthrew it. Haiti became the first Black republic and the only nation founded by a successful slave revolution.",
        "origin_routes": ["Bight of Benin (Fon, Ewe, Yoruba)", "West-Central Africa (Kongo)"],
        "ethnicities": ["Fon (Rada) heritage", "Kongo (Petwo) heritage"],
        "languages": ["Haitian Creole (Kreyòl)", "French (official)"],
        "religions": ["Vodou (synthesis of Fon Vodun, Kongo, and Catholic elements)", "Catholicism", "Protestantism"],
        "culture": "Vodou liturgical music, rara processional music, kompa, Haitian visual art (Hector Hyppolite, Préfète Duffaut), literature of Marie Vieux-Chauvet, Jacques Roumain, and Edwidge Danticat.",
        "story": "On 14 August 1791, the Bois Caïman ceremony, led by Vodou priest Dutty Boukman, is traditionally considered the spark of the Haitian Revolution. Toussaint Louverture organized the army that defeated French, Spanish, and British forces. Jean-Jacques Dessalines declared independence on 1 January 1804. France imposed a crippling indemnity in 1825 (~150 million francs) that Haiti paid until 1947 — a major cause of long-term economic struggle.",
        "modern": "Massive diasporas in Montreal, Miami, New York, and Paris; Michaëlle Jean (Governor General of Canada 2005–10) of Haitian origin; vibrant contemporary art and literature scene.",
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Laurent Dubois, 'Avengers of the New World' (2004)", "C.L.R. James, 'The Black Jacobins' (1938)"],
    },
    {
        "id": "afro-colombian",
        "name": "Afro-Colombian",
        "country": "Colombia", "country_iso2": "CO", "status": "documented",
        "region": "South America",
        "coords": [3.8961, -77.0379],  # Buenaventura
        "era_start": 1533,
        "era_end": 2025,
        "summary": "Cartagena was a major port of entry for Spanish South America; the Pacific coast (Chocó, Valle, Cauca) and the Palenques became core areas of Afro-Colombian life.",
        "origin_routes": ["West-Central Africa (Kongo, Angola)", "Senegambia"],
        "ethnicities": ["Palenquero (descendants of cimarrones)", "Raizal of San Andrés (English-speaking Caribbean diaspora)"],
        "languages": ["Colombian Spanish", "Palenquero (Spanish-Bantu creole, UNESCO Intangible Heritage)", "Raizal Creole English"],
        "religions": ["Catholicism", "African-derived ritual practices in the Pacific litany of 'arrullos'"],
        "culture": "Currulao, bullerengue, champeta (Caribbean coast), marimba de chonta tradition (UNESCO listed), writers Manuel Zapata Olivella and Mary Grueso Romero.",
        "story": "San Basilio de Palenque, founded near Cartagena around 1600 by Benkos Biohó, is recognized as the first free Black town in the Americas. The Pacific lowlands became one of the densest regions of Afro-descended settlement in Spanish America.",
        "modern": "Law 70 of 1993 recognized collective land rights for Afro-Colombian communities. The Pacific region remains underdeveloped and was disproportionately affected by Colombia's armed conflict.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Colombian DANE 2018 census", "Aquiles Escalante, 'El negro en Colombia' (1964)"],
    },
    {
        "id": "afro-european",
        "name": "Afro-European (Britain & France)",
        "country": "United Kingdom & France",
        "scope": "regional", "status": "documented",
        "region": "Europe",
        "coords": [51.5074, -0.1278],  # London
        "era_start": 1500,
        "era_end": 2025,
        "summary": "Long-established African presence in Europe was dramatically reshaped by post-WWII migration from former colonies — Windrush from the Caribbean to Britain (1948–) and migration from West and North Africa to France.",
        "origin_routes": ["Caribbean (Windrush generation)", "West Africa (Senegal, Mali, Côte d'Ivoire to France)", "Nigeria, Ghana to UK", "Central Africa (DRC to Belgium and France)"],
        "ethnicities": ["Caribbean-British (Jamaican, Barbadian, Trinidadian heritage)", "Black British African (Nigerian, Ghanaian)", "Sénégalais, Maliens, Antillais of French Republic"],
        "languages": ["English", "French", "Multicultural London English", "Verlan and youth-language features in France"],
        "religions": ["Christianity (Anglican, Pentecostal, Catholic)", "Islam (especially among West African and North African diasporas)"],
        "culture": "UK grime and drill, French rap and Afropop, Notting Hill Carnival (London) and the Caribbean carnival circuit, négritude literature (Aimé Césaire, Léopold Sédar Senghor, Léon-Gontran Damas — all Paris-based).",
        "story": "The 'Windrush generation' refers to Caribbean migrants who arrived in Britain from 1948 (HMT Empire Windrush) to fill post-war labor shortages. Stuart Hall and the Birmingham School redefined British cultural studies. The 1968 'Rivers of Blood' speech and the 1981 Brixton uprisings shaped the politics of race in Britain. In France, négritude in 1930s Paris reshaped Francophone literature.",
        "modern": "Black Lives Matter UK and France movements (2020–), British and French rap as dominant national pop forms, recurring debates on policing, colonial memory, and reparations.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Peter Fryer, 'Staying Power' (1984)", "Pap Ndiaye, 'La condition noire' (2008)"],
    },
    {
        "id": "afro-indian-ocean",
        "name": "Indian Ocean African Diasporas",
        "country": "Réunion, Mauritius, Madagascar, Gulf",
        "scope": "regional", "status": "documented",
        "region": "Indian Ocean",
        "coords": [-21.1151, 55.5364],  # Réunion
        "era_start": 700,
        "era_end": 2025,
        "summary": "The Indian Ocean is the oldest and longest African diaspora theatre — a thousand-year history of African migration to Arabia, Persia, India, and the Mascarene Islands, blending with Asian populations to create entirely new peoples.",
        "origin_routes": ["East Africa via the Swahili coast (Zanzibar, Kilwa)", "Madagascar (Malagasy themselves a Bantu-Austronesian people)", "Mozambique"],
        "ethnicities": ["Sidi of India (Habshi)", "Siddi of Pakistan", "Malagasy (Bantu-Austronesian fusion)", "Réunion Cafres", "Afro-Mauritians", "Afro-Iraqis and Afro-Saudis"],
        "languages": ["Réunion Creole and Mauritian Creole (French-based with African/Malagasy/Asian loans)", "Malagasy (Austronesian base, Bantu vocabulary)", "Gujarati and Konkani among Sidi"],
        "religions": ["Islam (Indian Ocean, Gulf, Sidi)", "Christianity (Mascarenes)", "African-influenced syncretism (Sidi Sufism in India)"],
        "culture": "Sega and maloya music of the Mascarenes (UNESCO Intangible Heritage), Sidi Goma drumming and Sufi practice in Gujarat, Malagasy hira gasy poetry.",
        "story": "Africans reached India as soldiers, sailors, and slaves from at least the 7th century. Malik Ambar, an Ethiopian-born ('Habshi') statesman, became regent of the Ahmadnagar sultanate in early 17th-century India and successfully resisted the Mughal Empire. The Indian Ocean slave trade continued legally until the late 19th century.",
        "modern": "Sidi community recognized as a Scheduled Tribe in India; Réunion and Mayotte as overseas departments of France; maloya as a marker of Réunion Creole identity since the 1970s.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Edward Alpers, 'The Indian Ocean in World History' (2014)", "Richard Eaton, 'The Rise of Islam and the Bengal Frontier' (1993)"],
    },
    {
        "id": "afro-mexican",
        "name": "Afro-Mexican",
        "country": "Mexico", "country_iso2": "MX", "status": "documented",
        "region": "North America",
        "coords": [16.7297, -98.7383],  # Costa Chica, Guerrero
        "era_start": 1519,
        "era_end": 2025,
        "summary": "New Spain imported roughly 200,000 Africans, more than any North American territory in the 16th–17th centuries. Today the Costa Chica of Guerrero and Oaxaca and the port of Veracruz remain the heart of Afro-Mexican life.",
        "origin_routes": ["West-Central Africa (Kongo, Angola)", "Bight of Benin", "Senegambia"],
        "ethnicities": ["Costa Chica Afro-Mexicans", "Jarocho communities of Veracruz", "Mascogos (Black Seminole descendants in Coahuila)"],
        "languages": ["Mexican Spanish (with Bantu and West African loanwords)", "Some Mascogo communities preserve Afro-Seminole Creole"],
        "religions": ["Catholicism with regional Afro-syncretic practices"],
        "culture": "Son jarocho (with the African-rooted jarana and quijada), fandango traditions, the Danza de los Diablos of the Costa Chica, the chilena dance.",
        "story": "Gaspar Yanga, a Kongolese-born leader, led a maroon revolt in Veracruz that in 1618 forced Spain to recognize San Lorenzo de los Negros — one of the first free Black settlements in the Americas. The Afro-Mexican contribution was long erased from the national mestizaje narrative.",
        "modern": "In 2015 INEGI's intercensal survey counted Afro-Mexicans for the first time (1.38 million); the 2020 census recorded 2.5 million. A constitutional reform in 2019 formally recognized Afro-Mexican peoples.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["INEGI 2020 census", "Bobby Vaughn, 'Race and Nation' (2005)", "Ben Vinson III, 'Bearing Arms for His Majesty' (2001)"],
    },
    {
        "id": "afro-indian-sidi",
        "name": "Sidi (Afro-Indian)",
        "country": "India",
        "country_iso2": "IN",
        "status": "documented",
        "region": "South Asia",
        "coords": [21.5222, 71.2090],  # Junagadh, Gujarat
        "era_start": 700,
        "era_end": 2025,
        "summary": "The Sidi (or Habshi) are descendants of East African Muslims and Bantu peoples who arrived in South Asia as sailors, soldiers, and slaves from the 7th century. Today communities of 50,000–70,000 live in Gujarat, Karnataka, Andhra Pradesh, and Hyderabad.",
        "origin_routes": ["East African coast (Zanzibar, Mozambique, Somalia)", "Ethiopian highlands (Habesha)"],
        "ethnicities": ["Sidi of Gujarat (Sufi shrine of Bava Gor)", "Siddi of Karnataka (Christian, Hindu, Muslim sub-groups)", "Makrani of Pakistan"],
        "languages": ["Gujarati", "Kannada", "Urdu", "Konkani", "fragments of Swahili in liturgical Sidi Goma chants"],
        "religions": ["Islam (Sufi orders, especially the Rifa'iyya)", "Hinduism", "Catholicism (among Karnataka Siddi)"],
        "culture": "Sidi Goma — Sufi devotional drumming and dance still performed at the shrine of Bava Gor in Gujarat; distinctive ngoma-style drums and call-and-response singing in a tradition unbroken for over five centuries.",
        "story": "Malik Ambar, born around 1548 in present-day Ethiopia, was sold into slavery, rose to become regent of the Ahmadnagar Sultanate, founded the city of Khirki (modern Aurangabad), and held off the Mughal Empire under Jahangir. The Sidi of Janjira ruled an island fortress off the Konkan coast from the 15th century to 1948 — never conquered by the Marathas or the British. The princely state of Sachin in Gujarat, founded in 1791, was likewise Sidi-ruled until 1948.",
        "modern": "The Sidi of Karnataka were recognized as a Scheduled Tribe in 2003. Sidi Goma troupes from Gujarat have toured internationally; ethnomusicologist Amy Catlin-Jairazbhoy has documented the tradition, and recent DNA studies have linked specific Sidi communities to particular Bantu and Habesha (Ethiopian) source populations.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Edward Alpers (ed.), 'Sidis and Scholars' (2004)", "Helene Basu, 'Habshi-Sklaven, Sidi-Fakire' (1995)", "Ababu Minda Yimene, 'An African Indian Community in Hyderabad' (2004)"],
    },
    {
        "id": "afro-german",
        "name": "Afro-German",
        "country": "Germany",
        "country_iso2": "DE",
        "status": "documented",
        "region": "Europe",
        "coords": [52.5200, 13.4050],
        "era_start": 1884,
        "era_end": 2025,
        "summary": "Afro-Germans (Schwarze Deutsche) descend from colonial-era migrants from German East and South-West Africa, postwar children of African American GIs, and late-20th-century African migration. Today they number an estimated 1 million.",
        "origin_routes": ["German colonial territories (Tanzania, Namibia, Cameroon, Togo)", "African American GI fathers (postwar 1945–)", "West African migration from 1980s"],
        "ethnicities": ["Descendants of colonial-era migrants from Cameroon/Togo/Tanzania", "Children of African American servicemen", "Recent migrants from Ghana, Nigeria, Senegal, DRC"],
        "languages": ["German", "English (US military heritage)", "African heritage languages in immigrant families"],
        "religions": ["Catholicism", "Protestantism", "Islam (newer African Muslim migration)"],
        "culture": "Afro-German feminist and literary movement of the 1980s — May Ayim (poet), Audre Lorde's residency in Berlin, the founding of ISD (Initiative Schwarze Menschen in Deutschland) in 1985. Contemporary Afro-German rap (Megaloh, Samy Deluxe).",
        "story": "Germany controlled Tanzania, Namibia, Cameroon, Togo, and parts of New Guinea from 1884 to 1919. The genocide of the Herero and Nama (1904–08) in present-day Namibia killed an estimated 80% of the Herero and 50% of the Nama — recognized as genocide by Germany in 2021. The term 'Afro-deutsch' was coined by May Ayim and the editors of 'Farbe bekennen' (1986).",
        "modern": "Germany formally recognized the Herero-Nama genocide in 2021 and pledged ~1.1 billion euros in development aid. The ISD continues to push for Afro-German representation; Aminata Touré became Schleswig-Holstein's first Black state minister in 2022.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["May Ayim et al., 'Farbe bekennen' (1986)", "Robbie Aitken & Eve Rosenhaft, 'Black Germany' (2013)"],
    },
    {
        "id": "afro-arab-gulf",
        "name": "Afro-Arab (Gulf & Levant)",
        "country": "Iraq, Saudi Arabia, Oman, Kuwait, Yemen",
        "scope": "regional", "status": "documented",
        "region": "Arabian Peninsula",
        "coords": [30.5085, 47.7804],  # Basra
        "era_start": 700,
        "era_end": 2025,
        "summary": "Centuries of African migration — initially as enslaved labor for southern Iraq's date and salt economy and as soldiers, sailors, pearl divers, and palace guards across the Gulf — produced enduring Black Arab communities in Basra, Hijaz, Yemen, and Oman.",
        "origin_routes": ["East African coast (Zanzibar, Tanzania, Kenya)", "Ethiopian highlands", "Sudanese Nile valley"],
        "ethnicities": ["Afro-Iraqis (especially around Basra)", "Akhdam of Yemen", "Afro-Omanis (post-Zanzibar 1964 return)", "Afro-Saudis of the Hijaz", "Afro-Kuwaitis"],
        "languages": ["Iraqi Arabic", "Gulf Arabic", "Swahili (still widely spoken in Oman and among Afro-Omanis)"],
        "religions": ["Sunni Islam", "Shia Islam (Iraq)", "Ibadi Islam (Oman)"],
        "culture": "Tanboura music — a six-stringed lyre identical to East African counterparts — and nuban / leiwa exorcism rituals practiced from Basra to Bahrain; the Liwa dance and ney-anbān (bagpipe) of the Gulf coast.",
        "story": "The Zanj Rebellion (869–883 CE), led by Ali ibn Muhammad, was one of the largest slave revolts in pre-modern history. Thousands of enslaved East Africans working the saltpans of southern Iraq rose up and held an autonomous polity for fifteen years. Centuries later, the Omani Sultanate of Zanzibar (1698–1964) tied the Gulf and East Africa tightly together; the 1964 Zanzibar Revolution brought tens of thousands of Afro-Omanis back across the sea.",
        "modern": "The Iraqi 'Free Iraqi Movement' (founded 2007) by Jalal Diyab campaigned for recognition of Afro-Iraqis as a minority. Afro-Omanis form a distinctive bilingual (Swahili-Arabic) presence in the Omani public service.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Alexandre Popovic, 'The Revolt of African Slaves in Iraq' (1999)", "Behnaz Mirzai et al., 'Slavery, Islam and Diaspora' (2009)"],
    },
]


# ---------- ETHNIC GROUPS / LANGUAGE FAMILIES ----------
ETHNIC_GROUPS = [
    {
        "id": "yoruba",
        "name": "Yoruba",
        "homeland": "Southwestern Nigeria, Benin, Togo",
        "coords": [7.3775, 3.9470],  # Ibadan
        "population": "≈ 47 million in West Africa, plus large diaspora",
        "language_family": "Niger-Congo · Volta-Niger",
        "summary": "One of the largest ethno-linguistic groups in Africa, organized historically into kingdoms (Ife, Oyo, Ijebu, Egba) and globally influential through diaspora religion (Orisha / Lucumí / Candomblé) and music.",
        "language": "Yoruba — a tonal language with millions of speakers and a long written literary tradition (Ajami and Latin scripts).",
        "religion": "Orisha tradition centered on Olodumare; large Christian and Muslim populations today.",
        "culture": "Talking drums (dùndún), aṣọ òkè textiles, Ifá divination corpus (UNESCO Intangible Heritage), bronze and terracotta art from Ife.",
        "diaspora": "Major heritage groups in Brazil (Candomblé), Cuba (Lucumí / Santería), Trinidad (Orisha), and the United States.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "sources": ["Robin Law, 'The Oyo Empire' (1977)", "UNESCO Ifá Inscription (2008)"],
    },
    {
        "id": "igbo",
        "name": "Igbo",
        "homeland": "Southeastern Nigeria",
        "coords": [6.2107, 7.0721],  # Onitsha
        "population": "≈ 35 million",
        "language_family": "Niger-Congo · Volta-Niger",
        "summary": "Historically organized in decentralized village democracies rather than centralized kingdoms, the Igbo developed distinctive market systems, masquerade arts, and the Nri ritual hegemony of the 10th–15th centuries.",
        "language": "Igbo — tonal, with many dialects and a strong contemporary literary tradition (Chinua Achebe, Chimamanda Ngozi Adichie).",
        "religion": "Traditional Odinala (centered on Chukwu and ancestor veneration); large Christian population today.",
        "culture": "Mbari art houses, uli body and wall painting, the Igbo-Ukwu bronzes (9th c., among the earliest lost-wax bronzes in sub-Saharan Africa).",
        "diaspora": "Significant Igbo heritage among African Americans (especially Virginia and the Carolinas) and Afro-Caribbeans (Jamaica, Barbados — Igbo influence on 'Eboe' identity).",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "sources": ["Thurstan Shaw, 'Igbo-Ukwu' (1970)", "Don Ohadike, 'Anioma' (1994)"],
    },
    {
        "id": "akan",
        "name": "Akan",
        "homeland": "Ghana and eastern Côte d'Ivoire",
        "coords": [6.6885, -1.6244],  # Kumasi
        "population": "≈ 27 million",
        "language_family": "Niger-Congo · Kwa",
        "summary": "A cluster of peoples including the Asante, Fante, Akuapem, Bono, and Akyem, unified by closely related languages and shared cultural institutions of matrilineal descent, the stool (state symbol), and a complex calendar.",
        "language": "Twi and Fante (mutually intelligible varieties of Akan); written in both Latin and Adinkra symbolic systems.",
        "religion": "Akan traditional religion (Nyame as supreme deity, lesser abosom and ancestor reverence); large Christian population today.",
        "culture": "Kente weaving, Adinkra symbols, the Asante goldweights (mrammuo), Akan funerary terra-cottas, the talking drum atumpan.",
        "diaspora": "The Coromantee identity in Jamaica and Suriname (e.g., Maroon leader Cudjoe was Akan); influence on Jamaican Patois grammar; persistent day-names (Kofi, Kwame, Kwesi) carried into the Americas.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "sources": ["T. C. McCaskie, 'State and Society in Pre-Colonial Asante' (1995)", "Kwame Anthony Appiah, 'In My Father's House' (1992)"],
    },
    {
        "id": "bantu",
        "name": "Bantu Language Family",
        "homeland": "Sub-equatorial Africa (from Cameroon to South Africa and east to Kenya)",
        "coords": [0.0, 20.0],
        "population": "≈ 350 million speakers across 500+ languages",
        "language_family": "Niger-Congo · Bantu",
        "summary": "The Bantu expansion (c. 3000 BCE – 500 CE) is one of the largest population movements in human history. From a homeland in present-day Cameroon, agriculturalists carrying iron-working and a shared linguistic stock spread across most of sub-equatorial Africa.",
        "language": "Over 500 Bantu languages including Swahili, Zulu, Xhosa, Kikuyu, Shona, Lingala, Kikongo, Kinyarwanda — all sharing core vocabulary and the distinctive noun-class system.",
        "religion": "Diverse, but with shared concepts of a high god, ancestor veneration, and ritual specialists; later Christianity, Islam, and African Independent Churches.",
        "culture": "Iron metallurgy (early sites at Lejja, Nigeria date to c. 2000 BCE), polyrhythmic music, the lamellophone (mbira / kalimba / sanza), and a vast oral-historical tradition.",
        "diaspora": "Bantu speakers form the demographic majority of nearly every transatlantic African diaspora — Brazilian Bantu heritage (Candomblé Angola), Caribbean Kongo religion (Palo Mayombe), the Kongo cosmogram in the United States Lowcountry.",
        "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Jan Vansina, 'Paths in the Rainforests' (1990)", "Koen Bostoen, 'The Bantu Expansion' (2018)"],
    },
]


# ---------- HERITAGE PLACES (clickable atlas points beyond civilizations) ----------
PLACES = [
    {"id": "lalibela", "name": "Rock-Hewn Churches of Lalibela", "type": "site", "coords": [12.0316, 39.0473], "era": "12th–13th c.", "blurb": "Eleven monolithic churches carved downward into volcanic rock, a UNESCO World Heritage Site and active place of Ethiopian Orthodox pilgrimage."},
    {"id": "timbuktu", "name": "Timbuktu", "type": "city", "coords": [16.7666, -3.0026], "era": "12th c. — present", "blurb": "Sahelian crossroads city famed for the Sankoré and Djinguereber centers of Islamic learning, with a manuscript heritage of hundreds of thousands of works."},
    {"id": "djenne", "name": "Great Mosque of Djenné", "type": "site", "coords": [13.9054, -4.5547], "era": "13th c. — present (rebuilt 1907)", "blurb": "The largest mud-brick building in the world, rebuilt each year in a community plastering festival (crépissage)."},
    {"id": "lake-turkana", "name": "Lake Turkana (Koobi Fora)", "type": "site", "coords": [3.5167, 36.3500], "era": "c. 1.5 Ma BP", "blurb": "One of the richest hominin fossil regions on Earth; the type site of Homo ergaster and 'Turkana Boy' (Nariokotome KNM-WT 15000)."},
    {"id": "olduvai", "name": "Olduvai Gorge", "type": "site", "coords": [-2.9833, 35.3500], "era": "c. 2 Ma BP", "blurb": "Tanzanian gorge where the Leakey family documented the Oldowan tool industry and early Homo habilis remains."},
    {"id": "lalibela2", "name": "Kilwa Kisiwani", "type": "city", "coords": [-8.9573, 39.5083], "era": "9th–16th c.", "blurb": "Swahili island city-state whose Great Mosque and palace (Husuni Kubwa) anchored Indian Ocean gold trade."},
    {"id": "elmina", "name": "Elmina Castle", "type": "site", "coords": [5.0851, -1.3520], "era": "1482 — present", "blurb": "Built by the Portuguese on Ghana's coast in 1482, the oldest European structure in sub-Saharan Africa and a major point of departure for the transatlantic trade."},
    {"id": "goree", "name": "Île de Gorée", "type": "site", "coords": [14.6664, -17.3987], "era": "15th–19th c.", "blurb": "Island off Dakar with the Maison des Esclaves, an enduring memorial of the transatlantic slave trade."},
    {"id": "palmares", "name": "Quilombo dos Palmares", "type": "site", "coords": [-9.5000, -36.6500], "era": "c. 1605–1694", "blurb": "The largest maroon community in the Americas, in present-day Alagoas, Brazil — at its peak home to perhaps 20,000 people."},
    {"id": "harlem", "name": "Harlem", "type": "neighborhood", "coords": [40.8116, -73.9465], "era": "1910s — present", "blurb": "Northern Manhattan neighborhood that became the cultural capital of Black America during the Harlem Renaissance and beyond."},
    {"id": "salvador", "name": "Pelourinho (Salvador da Bahia)", "type": "neighborhood", "coords": [-12.9714, -38.5014], "era": "16th c. — present", "blurb": "Historic center of colonial Salvador, the principal Atlantic port of entry for enslaved Africans to Brazil — today a UNESCO site and capital of Afro-Brazilian culture."},
    {"id": "zanzibar", "name": "Stone Town, Zanzibar", "type": "city", "coords": [-6.1659, 39.2026], "era": "9th c. — present", "blurb": "Swahili island city of coral-stone houses and carved doors; the 19th-century clove and slave market that connected East Africa to the Gulf and Indian Ocean."},
]


# ---------- LINEAGE JOURNEY (curated multi-stop narrative) ----------
LINEAGE_JOURNEY = {
    "id": "lineage-journey",
    "title": "Lineage Journey",
    "subtitle": "From the cradle of humankind to the soundtrack of the modern world",
    "blurb": "A 10-minute guided arc that connects four moments — origins, empire, dispersal, and creative rebirth — into a single human story.",
    "stops": [
        {
            "id": "origins",
            "heading": "I. The Cradle",
            "era": "c. 300,000 BCE",
            "place": "East African Rift",
            "story": "Anatomically modern humans appear in Africa. From Jebel Irhoud in Morocco to Omo Kibish in Ethiopia, the fossil record traces our species across the continent. Long before any 'out of Africa' moment, Africa was the cradle of every cultural and biological innovation that defines us.",
            "link": {"label": "Read the full story", "to": "/story/out-of-africa"},
            "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1600&q=80",
        },
        {
            "id": "mali",
            "heading": "II. The Empire",
            "era": "1324 CE",
            "place": "Niani → Cairo → Mecca",
            "story": "Mansa Musa of Mali sets out for Mecca with a caravan that contemporary chroniclers say flooded Cairo with so much gold that prices fell for years. Within decades, the Catalan Atlas depicts him on European maps holding a golden nugget — the wealthiest individual in recorded history before the 20th century.",
            "link": {"label": "Read the pilgrimage", "to": "/story/mansa-musa-hajj"},
            "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        },
        {
            "id": "passage",
            "heading": "III. The Passage",
            "era": "16th–19th c.",
            "place": "Atlantic Ocean",
            "story": "Across three and a half centuries, more than 12 million Africans are forced across the Atlantic. The journey is brutal and reshapes four continents. From the wreckage, captive peoples build new societies — quilombos at Palmares, maroon towns of Jamaica, Haitian revolutionaries — that the colonizing powers cannot fully contain.",
            "link": {"label": "Read the Middle Passage", "to": "/story/middle-passage"},
            "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1600&q=80",
        },
        {
            "id": "jazz",
            "heading": "IV. The Soundtrack",
            "era": "1900–1925",
            "place": "New Orleans → the world",
            "story": "On Sunday afternoons in Congo Square, the children and grandchildren of African captives kept drumming, dancing, and improvising. By 1917 the first jazz records are pressed. Within fifteen years, Duke Ellington plays the Cotton Club and a music born on the Mississippi has reached Paris, Berlin, Shanghai, and Bombay — and laid the foundation for nearly every popular genre that follows.",
            "link": {"label": "Read how jazz was born", "to": "/story/how-jazz-was-born"},
            "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1600&q=80",
        },
    ],
}


# ---------- ADDITIONAL CULTURAL FUSIONS ----------
EXTRA_CULTURE_ITEMS = [
    {"id": "gnawa", "category": "music", "region": "Morocco", "title": "Gnawa", "blurb": "Spiritual music of descendants of West African captives brought to Morocco, fusing Bantu and Sahelian rhythms with Sufi Islam; UNESCO Intangible Heritage since 2019."},
    {"id": "tango", "category": "music", "region": "Argentina / Uruguay (Diaspora)", "title": "Tango", "blurb": "Born in the late-19th-century Río de la Plata from candombe (an Afro-Uruguayan drumming tradition) fused with European immigrant music; the word itself likely derives from a Kongo source."},
    {"id": "afrobeats", "category": "music", "region": "West Africa & Diaspora", "title": "Afrobeats", "blurb": "21st-century pop genre originating in Lagos and Accra, fusing highlife, hip-hop, and Jamaican dancehall; global breakout of Wizkid, Burna Boy, Davido, Tems."},
    {"id": "cumbia", "category": "music", "region": "Colombia (Caribbean Coast)", "title": "Cumbia", "blurb": "Folkloric music of Colombia's Caribbean coast combining African drums (gaita, tambora), Indigenous flutes, and Spanish couplet form; today a continental Latin-American genre."},
    {"id": "hiphop-fusion", "category": "music", "region": "United States → Global", "title": "Hip-Hop", "blurb": "From 1970s Bronx block parties built by Jamaican-born DJ Kool Herc and his peers, hip-hop became the dominant global youth culture of the late 20th and 21st centuries."},
    {"id": "candombe", "category": "ritual", "region": "Uruguay (Diaspora)", "title": "Candombe", "blurb": "Afro-Uruguayan drumming and dance tradition descended from Kongo captives, performed in Montevideo's annual Llamadas processions; UNESCO Intangible Heritage 2009."},
]
