"""Seed content for AfroAtlas. Curated, source-grounded summaries."""

MODULES = [
    {
        "id": "origins",
        "order": 1,
        "title": "Origins",
        "subtitle": "The cradle of humankind",
        "blurb": "Human origins in Africa, early migrations, archaeology, genetics, and the dialogue between oral tradition and scientific consensus.",
        "era": "c. 300,000 BCE — 12,000 BCE",
        "tone_note": "Scientific consensus and oral traditions are presented separately and clearly labeled.",
    },
    {
        "id": "civilizations",
        "order": 2,
        "title": "African Civilizations",
        "subtitle": "Empires, kingdoms, and city-states",
        "blurb": "Structured profiles of Mali, Songhai, Kush/Nubia, Axum, Benin, Kongo, Great Zimbabwe, Swahili Coast, and North African civilizations.",
        "era": "c. 3100 BCE — 1900 CE",
    },
    {
        "id": "dispersal",
        "order": 3,
        "title": "Slavery & Dispersal",
        "subtitle": "Forced migration and resistance",
        "blurb": "Transatlantic and trans-Saharan slave trades, colonialism, resistance, maroon societies, abolition, and cultural survival.",
        "era": "7th c. — 19th c.",
        "tone_note": "Factual, non-sensational, historically grounded.",
    },
    {
        "id": "diaspora",
        "order": 4,
        "title": "Diaspora",
        "subtitle": "Communities of descent",
        "blurb": "African-descended communities across the Caribbean, Brazil and Latin America, the United States, Europe, and the Indian Ocean.",
        "era": "16th c. — present",
    },
    {
        "id": "impact",
        "order": 5,
        "title": "Global Cultural Impact",
        "subtitle": "Music, art, language, sport",
        "blurb": "Evidence-based influence on global music (jazz, blues, hip-hop, reggae, samba), fashion, dance, literature, sport, philosophy, and cuisine.",
        "era": "19th c. — present",
    },
    {
        "id": "knowledge",
        "order": 6,
        "title": "Knowledge & Innovation",
        "subtitle": "Science, medicine, engineering",
        "blurb": "Verified historical contributions in mathematics, medicine, agriculture, metallurgy, architecture, and navigation — sourced, not mythologized.",
        "era": "Antiquity — modern",
    },
    {
        "id": "culture",
        "order": 7,
        "title": "Culture Library",
        "subtitle": "Food, music, language, ritual",
        "blurb": "An immersive, region-by-region library of foods, instruments, languages, garments, proverbs, and spiritual practices.",
        "era": "Living traditions",
    },
    {
        "id": "migration",
        "order": 8,
        "title": "Migration & Identity",
        "subtitle": "Patterns and meaning",
        "blurb": "Human migration patterns, climate and geography, and the formation of identity over time — without racial pseudoscience.",
        "era": "Deep time — present",
    },
]

CIVILIZATIONS = [
    {
        "id": "mali",
        "name": "Mali Empire",
        "region": "West Africa",
        "modern_locations": ["Mali", "Senegal", "Gambia", "Guinea", "Niger", "Burkina Faso"],
        "coords": [16.7666, -3.0026],  # near Timbuktu
        "era_start": 1235,
        "era_end": 1670,
        "summary": "A vast West African empire founded by Sundiata Keita that grew rich from trans-Saharan gold and salt trade and became a renowned center of Islamic scholarship.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Federation of provinces under a Mansa (emperor); council of elders (Gbara) advised on customary law (Kouroukan Fouga).",
        "economy_and_trade": "Gold from Bambuk and Bure; salt from the Sahara; copper, kola nuts, ivory. Trans-Saharan caravans linked Timbuktu and Djenné to North Africa.",
        "science_and_knowledge": "Timbuktu's Sankoré and Djinguereber centers preserved manuscripts on astronomy, mathematics, medicine, and Islamic law. The Timbuktu manuscripts number in the hundreds of thousands.",
        "art_and_culture": "Sudano-Sahelian mud architecture (Djinguereber Mosque), griot oral tradition (jeliw), kora and balafon music, indigo and bogolan textiles.",
        "key_figures": [
            {"name": "Sundiata Keita", "role": "Founder (r. c. 1235–1255)"},
            {"name": "Mansa Musa", "role": "Emperor (r. c. 1312–1337), famed Hajj of 1324"},
            {"name": "Ibn Battuta", "role": "Moroccan chronicler who visited Mali in 1352"},
        ],
        "timeline": [
            {"year": 1235, "event": "Sundiata defeats Sumanguru at the Battle of Kirina."},
            {"year": 1324, "event": "Mansa Musa's pilgrimage to Mecca destabilizes Mediterranean gold prices."},
            {"year": 1375, "event": "Mali depicted on the Catalan Atlas; Mansa Musa shown holding a gold nugget."},
            {"year": 1433, "event": "Tuareg seize Timbuktu; the empire begins gradual decline."},
        ],
        "sources": ["UNESCO World Heritage (Timbuktu)", "Ibn Battuta, Rihla", "Catalan Atlas (1375)"],
    },
    {
        "id": "songhai",
        "name": "Songhai Empire",
        "region": "West Africa",
        "modern_locations": ["Mali", "Niger", "Nigeria", "Burkina Faso", "Senegal"],
        "coords": [16.2917, -0.0428],  # Gao
        "era_start": 1464,
        "era_end": 1591,
        "summary": "Successor to Mali, one of the largest empires in African history, centered on Gao and Timbuktu, with formal civil administration and a renowned university.",
        "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Centralized monarchy under the Askia; provinces administered by appointed governors; standing army and river navy on the Niger.",
        "economy_and_trade": "Gold, salt, slaves, cloth, and kola nuts moved through Gao, Timbuktu, and Djenné; trans-Saharan trade with Morocco and the Maghreb.",
        "science_and_knowledge": "Sankoré University at Timbuktu reached its peak; jurists like Ahmad Baba al-Timbukti wrote on law and theology.",
        "art_and_culture": "Sudano-Sahelian architecture; manuscript culture; Islamic scholarship integrated with local custom.",
        "key_figures": [
            {"name": "Sonni Ali Ber", "role": "Conqueror, founded the imperial phase (r. 1464–1492)"},
            {"name": "Askia Mohammad I", "role": "Reformer, expanded administration (r. 1493–1528)"},
            {"name": "Ahmad Baba", "role": "Jurist and scholar (1556–1627)"},
        ],
        "timeline": [
            {"year": 1468, "event": "Sonni Ali captures Timbuktu."},
            {"year": 1493, "event": "Askia Mohammad seizes power and standardizes administration."},
            {"year": 1591, "event": "Moroccan army defeats Songhai at Tondibi using firearms."},
        ],
        "sources": ["Tarikh al-Sudan", "Tarikh al-Fattash", "Ahmad Baba's writings"],
    },
    {
        "id": "kush",
        "name": "Kingdom of Kush (Nubia)",
        "region": "Northeast Africa",
        "modern_locations": ["Sudan", "Southern Egypt"],
        "coords": [18.5500, 31.8333],  # Meroë
        "era_start": -1070,
        "era_end": 350,
        "summary": "A Nile civilization that briefly ruled Egypt as the 25th Dynasty and later flourished at Meroë with its own script and ironworking economy.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Sacred monarchy; royal succession sometimes through matrilineal lines (Kandake / queen mothers).",
        "economy_and_trade": "Iron production at Meroë, gold from Nubian mines, cattle, ivory, ebony; trade with Egypt, the Red Sea, and inland Africa.",
        "science_and_knowledge": "Developed the Meroitic script (still only partially deciphered); advanced iron metallurgy; pyramid construction at Nuri and Meroë.",
        "art_and_culture": "Over 200 royal pyramids at Meroë, temples to Amun and the lion-god Apedemak, distinctive jewelry and pottery.",
        "key_figures": [
            {"name": "Piye", "role": "Founder of the 25th Dynasty of Egypt (r. c. 744–714 BCE)"},
            {"name": "Taharqa", "role": "Pharaoh and builder (r. 690–664 BCE)"},
            {"name": "Amanirenas", "role": "Kandake who resisted Rome (1st c. BCE)"},
        ],
        "timeline": [
            {"year": -744, "event": "Piye conquers Egypt, founding the 25th Dynasty."},
            {"year": -270, "event": "Royal capital moves to Meroë; pyramid building intensifies."},
            {"year": -24, "event": "Amanirenas raids Roman Egypt; treaty with Augustus follows."},
            {"year": 350, "event": "Aksumite king Ezana sacks Meroë."},
        ],
        "sources": ["UNESCO World Heritage (Meroë)", "Strabo, Geography", "Royal stelae of Piye and Taharqa"],
    },
    {
        "id": "axum",
        "name": "Kingdom of Aksum",
        "region": "Horn of Africa",
        "modern_locations": ["Ethiopia", "Eritrea"],
        "coords": [14.1306, 38.7250],
        "era_start": -100,
        "era_end": 940,
        "summary": "A trading empire on the Red Sea that minted its own coinage, raised monumental stelae, and was among the first states to adopt Christianity.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Monarchy (negus); territorial governors; influence reached across the Red Sea into South Arabia.",
        "economy_and_trade": "Indian Ocean trade in ivory, gold, frankincense, tortoiseshell; minted gold, silver, and bronze coins from the 3rd century CE.",
        "science_and_knowledge": "Ge'ez script and literature; stone engineering of the Aksum stelae (largest single carved monoliths in the ancient world).",
        "art_and_culture": "Stelae fields at Aksum, rock-hewn architecture, illuminated Ge'ez manuscripts after Christianization in the 4th century.",
        "key_figures": [
            {"name": "Ezana", "role": "King who adopted Christianity (r. c. 320–360 CE)"},
            {"name": "Kaleb", "role": "King, intervened in South Arabia (early 6th c.)"},
        ],
        "timeline": [
            {"year": 100, "event": "Aksum appears in the Periplus of the Erythraean Sea as a major emporium."},
            {"year": 330, "event": "Ezana converts to Christianity."},
            {"year": 525, "event": "Kaleb conquers Himyar in South Arabia."},
            {"year": 940, "event": "Decline of Aksum; political center shifts inland."},
        ],
        "sources": ["Periplus of the Erythraean Sea", "Ezana stone", "UNESCO World Heritage (Aksum)"],
    },
    {
        "id": "great-zimbabwe",
        "name": "Great Zimbabwe",
        "region": "Southern Africa",
        "modern_locations": ["Zimbabwe"],
        "coords": [-20.2730, 30.9344],
        "era_start": 1100,
        "era_end": 1450,
        "summary": "A stone-built city-state whose mortarless granite walls anchored a cattle and gold trading network reaching the Swahili Coast and the Indian Ocean.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Centralized kingship of the Shona-speaking Karanga; ritual authority concentrated at the Hill Complex.",
        "economy_and_trade": "Cattle wealth, gold mining on the plateau; traded with Kilwa via Sofala — Chinese porcelain and Persian glass have been excavated at the site.",
        "science_and_knowledge": "Mortarless dry-stone masonry of dressed granite; sophisticated cattle husbandry and water management.",
        "art_and_culture": "Soapstone Zimbabwe Birds (national symbol of modern Zimbabwe), elliptical Great Enclosure with conical tower.",
        "key_figures": [
            {"name": "Nyatsimba Mutota", "role": "Founder of the successor Mutapa state (15th c.)"},
            {"name": "Karl Mauch", "role": "European who reported the site in 1871; misattributed it to non-African builders, a claim later refuted by archaeologists"},
        ],
        "timeline": [
            {"year": 1100, "event": "Construction of the stone enclosures begins."},
            {"year": 1300, "event": "Peak population estimated at 18,000."},
            {"year": 1450, "event": "Site largely abandoned; political power shifts to the Mutapa state."},
        ],
        "sources": ["UNESCO World Heritage (Great Zimbabwe)", "Garlake, 'Great Zimbabwe' (1973)"],
    },
    {
        "id": "benin",
        "name": "Kingdom of Benin",
        "region": "West Africa",
        "modern_locations": ["Nigeria (Edo State)"],
        "coords": [6.3398, 5.6175],
        "era_start": 1180,
        "era_end": 1897,
        "summary": "A forest kingdom in present-day Nigeria celebrated for its bronze and ivory court arts and a walled capital of remarkable scale.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Divine kingship of the Oba; titled chiefs (Uzama and town/palace chiefs) balanced royal power.",
        "economy_and_trade": "Pepper, ivory, cloth, and (later) palm oil; relations with Portuguese traders from 1485.",
        "science_and_knowledge": "Lost-wax bronze casting at a technical level rivaling any contemporary tradition; vast city walls (the Walls of Benin) ran for thousands of kilometers.",
        "art_and_culture": "The Benin Bronzes — commemorative plaques, heads, and figures — chronicle court life and history.",
        "key_figures": [
            {"name": "Oba Ewuare", "role": "Reformer king (r. c. 1440–1473)"},
            {"name": "Oba Esigie", "role": "Patron of the arts (r. c. 1504–1550)"},
        ],
        "timeline": [
            {"year": 1440, "event": "Oba Ewuare reorganizes the kingdom and the capital."},
            {"year": 1485, "event": "First Portuguese contact via João Afonso de Aveiro."},
            {"year": 1897, "event": "British 'Punitive Expedition' loots the royal palace; the Bronzes are dispersed across European museums."},
        ],
        "sources": ["British Museum (Benin collection)", "Ling Roth, 'Great Benin' (1903)"],
    },
    {
        "id": "kongo",
        "name": "Kingdom of Kongo",
        "region": "Central Africa",
        "modern_locations": ["Angola", "DR Congo", "Republic of Congo", "Gabon"],
        "coords": [-6.2710, 14.2469],  # near Mbanza Kongo
        "era_start": 1390,
        "era_end": 1857,
        "summary": "A centralized West-Central African kingdom that engaged in early sustained diplomacy with Portugal and adopted Catholicism in the late 15th century.",
        "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Elective monarchy of the Manikongo; six core provinces ruled by appointed governors.",
        "economy_and_trade": "Cloth (raffia and palm fiber), copper, ivory, salt; later tragically central to the transatlantic slave trade.",
        "science_and_knowledge": "Sophisticated weaving and metalwork; Kongo cosmogram (dikenga) ritual symbolism.",
        "art_and_culture": "Nkisi power figures, woven textiles prized in Europe, syncretic Kongo Christianity.",
        "key_figures": [
            {"name": "Nzinga a Nkuwu (João I)", "role": "First Christian king (r. 1470–1509)"},
            {"name": "Afonso I (Mvemba a Nzinga)", "role": "Reformer who protested the slave trade (r. 1509–1542)"},
            {"name": "Kimpa Vita (Beatriz)", "role": "Prophet of the Antonian movement (1684–1706)"},
        ],
        "timeline": [
            {"year": 1483, "event": "Portuguese explorer Diogo Cão arrives at the Kongo River."},
            {"year": 1526, "event": "Afonso I writes to the Portuguese king protesting slave raiding."},
            {"year": 1665, "event": "Battle of Mbwila ends Kongo's unified power."},
        ],
        "sources": ["Letters of Afonso I", "John Thornton, 'The Kongolese Saint Anthony' (1998)"],
    },
    {
        "id": "swahili",
        "name": "Swahili Coast City-States",
        "region": "East Africa",
        "modern_locations": ["Kenya", "Tanzania", "Mozambique", "Comoros", "northern Madagascar"],
        "coords": [-8.9573, 39.5083],  # Kilwa
        "era_start": 800,
        "era_end": 1500,
        "summary": "A constellation of Indian Ocean trading cities — Kilwa, Mombasa, Lamu, Zanzibar — fusing Bantu, Arab, Persian, and Indian influences in a literate, cosmopolitan culture.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Independent city-states ruled by sultans; mercantile elites controlled trade.",
        "economy_and_trade": "Gold (via Sofala), ivory, mangrove timber, slaves; imported Chinese porcelain, Indian cotton, Persian glass.",
        "science_and_knowledge": "Kiswahili language (Bantu base, Arabic loanwords) written in Ajami; navigation across the monsoon-driven Indian Ocean.",
        "art_and_culture": "Coral-stone mosques and houses, ornate carved doors, Swahili poetry (utenzi, utendi).",
        "key_figures": [
            {"name": "Sultan al-Hasan ibn Sulaiman", "role": "Builder of Kilwa's Great Mosque (14th c.)"},
            {"name": "Ibn Battuta", "role": "Visited Kilwa in 1331 and praised its elegance"},
        ],
        "timeline": [
            {"year": 1000, "event": "Stone towns emerge along the coast."},
            {"year": 1331, "event": "Ibn Battuta visits Kilwa."},
            {"year": 1505, "event": "Portuguese sack Kilwa; coastal trade reorients."},
        ],
        "sources": ["UNESCO World Heritage (Kilwa Kisiwani)", "Ibn Battuta, Rihla", "Mark Horton, 'Shanga' (1996)"],
    },
    {
        "id": "egypt",
        "name": "Ancient Egypt",
        "region": "North Africa",
        "modern_locations": ["Egypt"],
        "coords": [25.6872, 32.6396],  # Luxor
        "era_start": -3100,
        "era_end": -30,
        "summary": "One of the longest-lived civilizations in human history, anchored on the Nile, that produced monumental architecture, writing, medicine, and a continuous religious tradition.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Theocratic monarchy of the pharaoh; centralized bureaucracy of viziers, nomarchs, and scribes.",
        "economy_and_trade": "Nile agriculture (emmer wheat, barley, flax); trade with Nubia, Punt, the Levant, and the Aegean.",
        "science_and_knowledge": "Hieroglyphic and hieratic writing, advanced surveying and geometry, surgical and herbal medicine (Edwin Smith and Ebers papyri), 365-day calendar.",
        "art_and_culture": "Pyramids of Giza, temples at Karnak and Luxor, tomb painting, sculpture of unmatched continuity.",
        "key_figures": [
            {"name": "Narmer", "role": "Unified Upper and Lower Egypt (c. 3100 BCE)"},
            {"name": "Hatshepsut", "role": "Female pharaoh (r. 1479–1458 BCE)"},
            {"name": "Ramesses II", "role": "Long-reigning builder (r. 1279–1213 BCE)"},
        ],
        "timeline": [
            {"year": -3100, "event": "Unification of Upper and Lower Egypt."},
            {"year": -2560, "event": "Great Pyramid of Khufu completed."},
            {"year": -1279, "event": "Reign of Ramesses II begins."},
            {"year": -30, "event": "Death of Cleopatra VII; Egypt becomes a Roman province."},
        ],
        "sources": ["UNESCO World Heritage (Memphis, Thebes)", "Edwin Smith Papyrus", "Manetho, Aegyptiaca"],
    },
    {
        "id": "asante",
        "name": "Asante Empire",
        "region": "West Africa",
        "modern_locations": ["Ghana", "Côte d'Ivoire", "Togo"],
        "coords": [6.6885, -1.6244],  # Kumasi
        "era_start": 1701,
        "era_end": 1957,
        "summary": "A powerful Akan confederation founded by Osei Tutu around the sacred Golden Stool, famed for its goldwork, kente weaving, and sustained resistance to British colonialism.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Federation of Akan states under the Asantehene at Kumasi; the Golden Stool (Sika Dwa Kofi) embodied the soul of the nation. Council of paramount chiefs (Asantemanhyiamu) shared authority.",
        "economy_and_trade": "Alluvial gold from Akan forests, kola nuts, and rubber; long-distance trade north to the Sahel and south to European coastal forts.",
        "science_and_knowledge": "Adinkra symbolic writing, sophisticated weights-and-measures system for gold dust (mrammuo), and a high tradition of metalwork.",
        "art_and_culture": "Kente cloth (silk and cotton woven on narrow looms), Adinkra cloth, gold regalia of the royal court, talking drums (atumpan).",
        "key_figures": [
            {"name": "Osei Tutu I", "role": "Founder; unified the Akan under the Golden Stool (r. c. 1695–1717)"},
            {"name": "Okomfo Anokye", "role": "Priest and statesman who, by tradition, summoned the Golden Stool"},
            {"name": "Yaa Asantewaa", "role": "Queen mother of Ejisu who led the 1900 War of the Golden Stool against the British"},
        ],
        "timeline": [
            {"year": 1701, "event": "Asante defeats Denkyira at the Battle of Feyiase; the empire is consolidated."},
            {"year": 1817, "event": "Thomas Bowdich publishes his account of an embassy to Kumasi."},
            {"year": 1874, "event": "British sack Kumasi in the Third Anglo-Asante War."},
            {"year": 1900, "event": "Yaa Asantewaa leads the War of the Golden Stool."},
            {"year": 1957, "event": "Ghana becomes independent; the Asantehene retains traditional authority."},
        ],
        "sources": ["T. C. McCaskie, 'State and Society in Pre-Colonial Asante' (1995)", "Ivor Wilks, 'Asante in the Nineteenth Century' (1975)"],
    },
    {
        "id": "zulu",
        "name": "Zulu Kingdom",
        "region": "Southern Africa",
        "modern_locations": ["South Africa (KwaZulu-Natal)", "Eswatini"],
        "coords": [-28.5306, 31.4961],  # near uMgungundlovu
        "era_start": 1816,
        "era_end": 1897,
        "summary": "A southern African kingdom forged by Shaka kaSenzangakhona from Nguni chiefdoms, whose military reforms reshaped the region (the Mfecane) and famously defeated the British at Isandlwana.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Centralized monarchy of the inkosi; age-regiment system (amabutho) of standing military service; royal homestead at uMgungundlovu, later Ulundi.",
        "economy_and_trade": "Cattle wealth measured social and political standing; agriculture (sorghum, maize); regional and later European trade in ivory and hides.",
        "science_and_knowledge": "Tactical innovations attributed to Shaka — short stabbing iklwa, encircling 'horns of the buffalo' formation, hardened conscript regiments. Praise-poetry (izibongo) as oral historical record.",
        "art_and_culture": "Beadwork with coded symbolism, hide shields, woven grasswork; izibongo praise-poetry of the kings.",
        "key_figures": [
            {"name": "Shaka kaSenzangakhona", "role": "Founder-king (r. c. 1816–1828)"},
            {"name": "Dingane", "role": "Successor who confronted the Boer Voortrekkers (r. 1828–1840)"},
            {"name": "Cetshwayo kaMpande", "role": "King during the Anglo-Zulu War (r. 1872–1879)"},
        ],
        "timeline": [
            {"year": 1816, "event": "Shaka assumes leadership and reorganizes the Zulu military."},
            {"year": 1828, "event": "Shaka assassinated by half-brothers Dingane and Mhlangana."},
            {"year": 1879, "event": "Zulu impis annihilate a British column at Isandlwana on 22 January."},
            {"year": 1897, "event": "Zululand annexed into the Colony of Natal."},
        ],
        "sources": ["John Laband, 'The Rise and Fall of the Zulu Nation' (1997)", "Carolyn Hamilton (ed.), 'The Mfecane Aftermath' (1995)"],
    },
    {
        "id": "hausa",
        "name": "Hausa City-States",
        "region": "West Africa",
        "modern_locations": ["Nigeria (Kano, Katsina, Zaria)", "Niger"],
        "coords": [12.0022, 8.5919],  # Kano
        "era_start": 1000,
        "era_end": 1804,
        "summary": "A network of seven autonomous Hausa city-states (the Hausa Bakwai) that thrived as Sahelian trade and craft hubs — Kano in textiles and leather, Katsina in scholarship — until the Sokoto jihad of the early 19th century.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Independent city-states each ruled by a sarki (king); titled offices and council government; walled cities with elaborate gate systems.",
        "economy_and_trade": "Indigo-dyed cloth, leather, salt, kola, and grain; Kano's dye pits operated continuously from the 15th century. Trans-Saharan caravans linked the cities to North Africa.",
        "science_and_knowledge": "Strong Islamic scholarly tradition, especially at Katsina; Ajami script (Hausa in Arabic letters) used for poetry and law.",
        "art_and_culture": "Distinctive Hausa architecture (mud-vault domes, painted facades), embroidered babbar riga robes, kakaki ceremonial trumpets.",
        "key_figures": [
            {"name": "Queen Amina of Zazzau", "role": "Warrior-queen of Zaria (late 16th c.), credited with city walls (ganuwar Amina)"},
            {"name": "Muhammadu Rumfa", "role": "Sarkin Kano (r. 1463–1499), reformed the city and built the central mosque"},
            {"name": "Usman dan Fodio", "role": "Scholar who led the 1804 jihad founding the Sokoto Caliphate"},
        ],
        "timeline": [
            {"year": 1100, "event": "Bayajidda legend dates the founding of the Hausa Bakwai (preserved in the Kano Chronicle)."},
            {"year": 1463, "event": "Reign of Muhammadu Rumfa begins; Kano consolidates its administrative reforms."},
            {"year": 1804, "event": "Usman dan Fodio's jihad begins; most Hausa states are incorporated into the Sokoto Caliphate."},
        ],
        "sources": ["The Kano Chronicle", "Murray Last, 'The Sokoto Caliphate' (1967)"],
    },
    {
        "id": "ethiopia",
        "name": "Medieval Ethiopia (Solomonic Dynasty)",
        "region": "Horn of Africa",
        "modern_locations": ["Ethiopia", "Eritrea"],
        "coords": [12.0316, 39.0473],  # Lalibela
        "era_start": 1270,
        "era_end": 1769,
        "summary": "Successor to Aksum, a Christian highland kingdom that produced the rock-hewn churches of Lalibela, the manuscript culture of the Zagwe and Solomonic courts, and the only African state to repel European colonization at Adwa (1896).",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "political_structure": "Sacred monarchy of the Solomonic line (negusä nägäst, 'king of kings'); mobile court (katama); regional rases governing provinces.",
        "economy_and_trade": "Highland agriculture (teff, wheat, coffee), gold, slaves, and ivory traded down to Red Sea ports; later coffee export from Kaffa.",
        "science_and_knowledge": "Ge'ez literary and ecclesiastical tradition; chronicles (e.g., Kebra Nagast — 'Glory of the Kings'), illuminated gospels; complex church music (zema).",
        "art_and_culture": "Eleven rock-hewn churches of Lalibela (12th–13th c.), castles of Gondar (17th c.), monastic painting on Lake Tana islands.",
        "key_figures": [
            {"name": "Yekuno Amlak", "role": "Founder of the Solomonic dynasty (r. 1270–1285)"},
            {"name": "Zara Yaqob", "role": "Reformer emperor and theologian (r. 1434–1468)"},
            {"name": "Empress Mentewab", "role": "Regent of Gondar (mid-18th c.), patron of architecture"},
        ],
        "timeline": [
            {"year": 1270, "event": "Yekuno Amlak founds the Solomonic dynasty."},
            {"year": 1320, "event": "Rock-hewn churches of Lalibela completed under the late Zagwe and early Solomonic kings."},
            {"year": 1636, "event": "Emperor Fasilides founds Gondar as a permanent capital."},
            {"year": 1769, "event": "Zemene Mesafint ('Era of the Princes') begins; central authority weakens."},
        ],
        "sources": ["UNESCO World Heritage (Lalibela, Gondar)", "Kebra Nagast", "Donald Crummey, 'Land and Society in the Christian Kingdom of Ethiopia' (2000)"],
    },
]

STORIES = [
    {
        "id": "mansa-musa-hajj",
        "title": "The Pilgrimage of Mansa Musa",
        "civilization_id": "mali",
        "era": "1324 CE",
        "summary": "How the Mansa of Mali turned a pilgrimage into a diplomatic and economic event remembered across three continents.",
        "chapters": [
            {"heading": "Departure from Niani", "body": "In 1324, Mansa Musa set out across the Sahara with a caravan that contemporary chroniclers numbered in the tens of thousands. The procession carried staff, scholars, and a great quantity of gold to fund the journey and the charity expected of a pilgrim king."},
            {"heading": "Arrival in Cairo", "body": "The Mamluk historian al-Umari, writing about a decade later, reported that Mansa Musa's spending in Cairo so flooded the local market with gold that its value fell sharply and took years to recover. He met with Sultan al-Nasir Muhammad and was widely received as a sovereign of the highest rank."},
            {"heading": "Mecca and Medina", "body": "After completing the rites of the Hajj, Musa returned by way of Cairo accompanied by scholars and architects, including, by some accounts, the Andalusian poet and architect Abu Ishaq al-Sahili, who is associated with later building projects in Timbuktu."},
            {"heading": "Legacy on the Catalan Atlas", "body": "Half a century later, in 1375, the Majorcan cartographer Abraham Cresques depicted Mansa Musa on the Catalan Atlas holding a golden nugget — a sign of how vividly the memory of his journey persisted in European geographic imagination."},
        ],
        "sources": ["al-Umari, Masalik al-absar", "Ibn Khaldun, Muqaddimah", "Catalan Atlas (1375)"],
    },
    {
        "id": "out-of-africa",
        "title": "Out of Africa",
        "civilization_id": None,
        "era": "c. 70,000 BCE",
        "summary": "The current scientific consensus on how anatomically modern humans expanded from Africa across the globe, and what oral traditions add to the story.",
        "chapters": [
            {"heading": "Anatomically Modern Humans", "body": "Fossils from Jebel Irhoud in Morocco (c. 300,000 BP) and Omo Kibish in Ethiopia (c. 195,000 BP) are among the earliest remains attributed to Homo sapiens. Genetic and archaeological evidence supports an African origin for our species."},
            {"heading": "The Major Dispersal", "body": "Most genetic studies date a major out-of-Africa dispersal to roughly 70,000–60,000 years ago, with earlier excursions attested by sites such as Misliya Cave in present-day Israel (c. 180,000 BP)."},
            {"heading": "Encounters", "body": "Modern humans interbred with Neanderthals and Denisovans; most people outside sub-Saharan Africa carry small amounts of Neanderthal DNA, and many populations in Oceania also carry Denisovan ancestry."},
            {"heading": "Oral Traditions", "body": "Many African societies preserve detailed origin narratives — Dogon, Yoruba, San — that are cultural and spiritual heritage in their own right. We present them as such, separately from the genetic and archaeological record."},
        ],
        "sources": ["Hublin et al., Nature 2017 (Jebel Irhoud)", "Mallick et al., Nature 2016 (SGDP)"],
    },
    {
        "id": "middle-passage",
        "title": "The Middle Passage",
        "civilization_id": None,
        "era": "16th–19th c.",
        "summary": "An evidence-based account of the transatlantic crossing — its scale, conditions, resistance, and the demographic transformation of the Americas.",
        "chapters": [
            {"heading": "Scale", "body": "The Trans-Atlantic Slave Trade Database (Slavevoyages.org) records roughly 36,000 documented voyages between 1514 and 1866, embarking an estimated 12.5 million Africans. About 10.7 million disembarked in the Americas; the difference reflects the staggering mortality of the crossing."},
            {"heading": "The Ships", "body": "Slavers were typically modified merchant vessels packed below decks. Voyages averaged six to ten weeks from West and West-Central African coasts; mortality on the passage averaged roughly 12–15% across the period, varying by route and era."},
            {"heading": "Resistance", "body": "Shipboard insurrections are documented on hundreds of voyages — the Amistad case of 1839 being the most famous. Once in the Americas, enslaved Africans built maroon societies from Palmares in Brazil (which lasted nearly a century) to the Saramaka and Ndyuka of Suriname."},
            {"heading": "Abolition", "body": "British abolition of the trade in 1807, U.S. abolition in 1808, and Brazilian abolition in 1850–88 progressively closed the legal trade. Smuggling continued for decades. The last documented voyage (the Clotilda) arrived in Mobile, Alabama in 1860."},
        ],
        "sources": ["Slavevoyages.org (Trans-Atlantic Slave Trade Database)", "David Eltis & David Richardson, 'Atlas of the Transatlantic Slave Trade' (2010)"],
    },
    {
        "id": "how-jazz-was-born",
        "title": "How Jazz Was Born",
        "civilization_id": None,
        "era": "Late 19th — early 20th c.",
        "summary": "A grounded history of how West and Central African musical traditions, blended with European harmony in New Orleans, produced the most influential genre of the 20th century.",
        "chapters": [
            {"heading": "Roots in West Africa", "body": "Call-and-response phrasing, polyrhythm, blue notes, and improvisation across a shared groove are all features of West and Central African musical traditions. Enslaved Africans carried these structural habits across the Atlantic, where they survived in field hollers, work songs, ring shouts, and the spirituals."},
            {"heading": "Congo Square", "body": "In antebellum New Orleans, the city's unusual Code Noir allowed enslaved people to gather on Sundays at Place des Nègres (Congo Square). Travelers documented drumming, dancing, and an instrumental vocabulary that combined African, Caribbean, and European elements."},
            {"heading": "Blues, Ragtime, and the New Sound", "body": "After Reconstruction, the blues emerged in the Mississippi Delta, ragtime in Sedalia and St. Louis (Scott Joplin's 'Maple Leaf Rag' was published in 1899). New Orleans brass bands fused these with marches and dance music. By the 1910s, players like Buddy Bolden, Joe 'King' Oliver, and the young Louis Armstrong were doing something new."},
            {"heading": "Global Reach", "body": "The first jazz recording (Original Dixieland Jass Band) appeared in 1917. Within fifteen years, Duke Ellington was leading at the Cotton Club, and jazz had reached Paris, Berlin, Shanghai, and Bombay. It became the substrate for almost every popular-music genre that followed — rhythm and blues, soul, rock, funk, hip-hop."},
        ],
        "sources": ["Gunther Schuller, 'Early Jazz' (1968)", "Ned Sublette, 'The World That Made New Orleans' (2008)", "Library of Congress, American Folklife Center"],
    },
]

CULTURE_ITEMS = [
    {"id": "jollof", "category": "food", "region": "West Africa", "title": "Jollof Rice", "blurb": "A one-pot rice dish whose Senegambian ancestor (thieboudienne) traveled with the Wolof along West African trade routes and inspired countless national versions."},
    {"id": "kora", "category": "music", "region": "West Africa", "title": "The Kora", "blurb": "A 21-stringed bridge harp central to the Mande griot tradition; jeli families have transmitted its repertoire orally for many generations."},
    {"id": "kente", "category": "clothing", "region": "Ghana", "title": "Kente Cloth", "blurb": "Hand-woven silk and cotton strips of the Asante and Ewe, each pattern named and carrying proverbial meaning."},
    {"id": "swahili-language", "category": "language", "region": "East Africa", "title": "Kiswahili", "blurb": "A Bantu language with substantial Arabic loanwords that became the lingua franca of the East African coast and now an official language of the African Union."},
    {"id": "capoeira", "category": "ritual", "region": "Brazil (Diaspora)", "title": "Capoeira", "blurb": "An Afro-Brazilian martial art and dance developed by enslaved Africans, drawing on Central African body movement and music."},
    {"id": "samba", "category": "music", "region": "Brazil (Diaspora)", "title": "Samba", "blurb": "Born in the early 20th century in Rio de Janeiro from West and Central African rhythmic traditions carried by the diaspora."},
    {"id": "akan-proverb", "category": "proverbs", "region": "Ghana", "title": "Sankofa", "blurb": "An Akan symbol and proverb: 'Se wo were fi na wosankofa a yenkyi' — it is not wrong to go back for that which you have forgotten."},
    {"id": "injera", "category": "food", "region": "Ethiopia / Eritrea", "title": "Injera", "blurb": "A spongy sourdough flatbread made from teff, the staple grain of the Ethiopian highlands for millennia."},
    {"id": "blues", "category": "music", "region": "United States (Diaspora)", "title": "The Blues", "blurb": "A 19th–20th century African American genre rooted in field hollers and spirituals; the foundation of rock, soul, and much of modern popular music."},
    {"id": "reggae", "category": "music", "region": "Jamaica (Diaspora)", "title": "Reggae", "blurb": "Emerging in late-1960s Jamaica from ska and rocksteady, deeply tied to Rastafari thought and Pan-African consciousness."},
    {"id": "ndebele", "category": "clothing", "region": "Southern Africa", "title": "Ndebele Beadwork", "blurb": "Vivid geometric beadwork and mural painting of the Ndebele people of South Africa, traditionally signaling life stages of women."},
    {"id": "yoruba-orisha", "category": "spiritual", "region": "Nigeria & Diaspora", "title": "Orisha Traditions", "blurb": "Yoruba religious traditions surviving and transforming across the Atlantic as Candomblé in Brazil and Lucumí/Santería in Cuba."},
]

MIGRATION_ROUTES = [
    {
        "id": "out-of-africa-southern-route",
        "name": "Sortie d'Afrique — route méridionale (via Bab-el-Mandeb)",
        "era": "c. 70,000–50,000 BCE",
        "era_start": -70000, "era_end": -50000,
        "color": "#D4AF37",
        "points": [[9.0, 43.0], [12.5, 45.0], [18.0, 55.0], [15.0, 73.0], [5.0, 100.0], [-2.0, 118.0], [-12.4, 130.8]],
        "summary": "One of two proposed major dispersal routes out of Africa: early modern humans crossed the Bab-el-Mandeb strait from the Horn of Africa into Arabia, then followed the Indian Ocean coastline through South and Southeast Asia, eventually reaching Sahul (Australia/New Guinea) — the earliest known settlement there, at Madjedbebe, dates to roughly 65,000–50,000 years ago. Exact dates remain debated among researchers.",
        "sources": ["Lahr & Foley multiple-dispersals model, cited in López, Van Dorp & Hellenthal, 'Human Dispersal Out of Africa: A Lasting Debate' (2015)", "Madjedbebe site dating, Northern Australia"],
    },
    {
        "id": "out-of-africa-northern-route",
        "name": "Sortie d'Afrique — route septentrionale (via le Levant)",
        "era": "c. 56,000–40,000 BCE",
        "era_start": -56000, "era_end": -40000,
        "color": "#B8952E",
        "points": [[30.0, 31.2], [31.8, 35.2], [37.0, 35.0], [45.0, 30.0], [48.0, 16.0]],
        "summary": "The second proposed major dispersal route: modern humans moved north via the Nile and Sinai into the Levant, then spread across Western Eurasia. This route is associated with the earliest confirmed Homo sapiens presence in Europe, roughly 40,000 years ago — the period when modern humans first encountered and interbred with Neanderthal populations there.",
        "sources": ["López, Van Dorp & Hellenthal, 'Human Dispersal Out of Africa: A Lasting Debate' (2015)", "Genomic divergence-time estimates, Eurasian vs. African populations"],
    },
    {
        "id": "peopling-of-the-americas",
        "name": "Peuplement des Amériques (via le détroit de Béring)",
        "era": "c. 20,000–15,000 BCE",
        "era_start": -20000, "era_end": -15000,
        "color": "#8A6F1F",
        "points": [[65.0, 90.0], [66.0, -170.0], [64.8, -147.7], [19.4, -99.1], [-13.5, -71.9]],
        "summary": "Long after the initial dispersals out of Africa, descendant populations in Siberia crossed the Bering land bridge (exposed during the Last Glacial Maximum) into the Americas, roughly 15,000–20,000 years ago, eventually spreading south across both continents. This is a distinct, much later wave than the original African dispersals.",
        "sources": ["Bering land bridge migration chronology, Last Glacial Maximum sea-level evidence"],
    },
    {
        "id": "trans-saharan",
        "name": "Trans-Saharan Trade",
        "era": "c. 700–1500 CE",
        "era_start": 700, "era_end": 1500,
        "color": "#C18C42",
        "points": [[16.77, -3.00], [25.00, -2.00], [31.00, 1.00], [34.02, -6.83]],
        "summary": "Camel caravans crossed the Sahara for centuries, linking West African kingdoms (Ghana, Mali, Songhai) to North Africa and the Mediterranean world. Gold and enslaved people moved north; salt, textiles, and horses moved south. This exchange also carried Islam and literacy deep into West Africa, fueling cities like Timbuktu and Gao.",
        "sources": ["Standard historiography of the Ghana, Mali and Songhai empires; trans-Saharan trade route scholarship"],
    },
    {
        "id": "indian-ocean",
        "name": "Indian Ocean Trade",
        "era": "c. 800–1500 CE",
        "era_start": 800, "era_end": 1500,
        "color": "#A0522D",
        "points": [[-8.95, 39.50], [-1.30, 36.80], [12.78, 45.03], [19.07, 72.87], [22.30, 114.20]],
        "summary": "Monsoon winds linked the Swahili coast of East Africa to Arabia, India, and beyond in a centuries-old commercial network trading gold, ivory, and textiles. From roughly the 9th century, this network also carried a large-scale slave trade — East Africans (the term 'Zanj' was used in medieval Arabic sources) were trafficked to the Middle East and the Indian Ocean islands, a trade that continued, under Omani/Zanzibari control, into the 19th century.",
        "sources": ["Slavery in Zanzibar (Wikipedia, citing Omani-Zanzibari historical records)", "East Africa in the Early Indian Ocean World Slave Trade: The Zanj Revolt Reconsidered (academic chapter)"],
    },
    {
        "id": "transatlantic",
        "name": "Transatlantic Forced Migration",
        "era": "16th–19th c.",
        "era_start": 1500, "era_end": 1888,
        "color": "#7B2D26",
        "points": [[6.34, 5.62], [-6.27, 14.25], [-15.78, -47.93], [18.47, -69.95], [29.95, -90.07]],
        "summary": "Between the 16th and 19th centuries, European traders forcibly transported an estimated 12.5 million enslaved Africans across the Atlantic; roughly 10.7 million survived the Middle Passage, disembarking mainly in Brazil, the Caribbean, and North America. This is the historical foundation of the African diaspora across the Americas.",
        "sources": ["Henry Louis Gates Jr., cited by Re-Imagining Migration project (reimaginingmigration.org)", "Slave Voyages Database (established transatlantic slave trade scholarship)"],
    },
    {
        "id": "bantu-expansion",
        "name": "Bantu Expansion",
        "era": "c. 1500 BCE – 500 CE",
        "era_start": -1500, "era_end": 500,
        "color": "#8B5A2B",
        "points": [[6.0, 10.0], [2.0, 20.0], [-4.0, 25.0], [-12.0, 28.0], [-20.0, 28.0], [-26.0, 31.0]],
        "summary": "Speakers of early Bantu languages spread gradually from a homeland near the Nigeria-Cameroon border across Central, Eastern, and Southern Africa over roughly two thousand years, bringing agriculture and ironworking and eventually giving rise to the majority of Bantu-speaking peoples across the southern half of the continent today.",
        "sources": ["Standard linguistic and archaeological Bantu expansion scholarship"],
    },
    {
        "id": "austronesian-expansion",
        "name": "Austronesian Expansion (Out of Taiwan)",
        "era": "c. 3000 BCE – 1250 CE",
        "era_start": -3000, "era_end": 1250,
        "color": "#4A7C82",
        "points": [[23.5, 121.0], [14.6, 121.0], [-2.0, 118.0], [-8.5, 125.6], [-17.7, 168.3], [-17.7, -149.4], [-21.2, -159.8], [-38.7, 176.1]],
        "summary": "Austronesian-speaking peoples spread from Taiwan across Southeast Asia and the Pacific over several thousand years. One branch sailed west across the Indian Ocean, reaching and settling Madagascar (likely by the first millennium CE) — this African connection is why the Malagasy language today is Austronesian, not African, in origin, a notable exception on the African continent.",
        "sources": ["Austronesian expansion and Madagascar settlement scholarship (linguistic and archaeological consensus)"],
    },
    {
        "id": "islamic-conquest-maghreb",
        "name": "Islamic Conquest of the Maghreb",
        "era": "647–709 CE",
        "era_start": 647, "era_end": 709,
        "color": "#6B7A3A",
        "points": [[30.05, 31.25], [32.90, 13.19], [36.85, 10.19], [33.57, -7.60]],
        "summary": "Following the death of Muhammad in 632, Arab Muslim armies expanded west from Egypt, reaching the Maghreb from 647 CE onward under the Rashidun and then Umayyad caliphates. Carthage fell in 698, and the conquest concluded by 709 with the capture of Ceuta, bringing North Africa into the Islamic world and eventually spreading Islam and Arabic across the region.",
        "sources": ["Muslim conquest of the Maghreb — standard historiography (e.g. history-maps.com, Humanities LibreTexts)"],
    },
    {
        "id": "great-migration-us",
        "name": "Great Migration (African American)",
        "era": "1916–1970",
        "era_start": 1916, "era_end": 1970,
        "color": "#B8860B",
        "points": [[32.37, -86.30], [41.88, -87.63], [42.33, -83.05], [40.71, -74.01], [34.05, -118.24]],
        "summary": "Between 1916 and 1970, roughly six million African Americans left the rural South for cities in the North, Midwest, and West, driven by Jim Crow segregation, racial violence, and sharecropping poverty, and pulled by wartime industrial jobs. The movement reshaped American cities, fueled the Harlem Renaissance, and built the urban Black communities that later powered the civil rights movement.",
        "sources": ["Encyclopaedia Britannica, 'Great Migration'", "Isabel Wilkerson, The Warmth of Other Suns (2010)"],
    },
]

