"""Notable Figures across African and African-descended history."""

# Categories: queens, kings, rulers, military, scientists, inventors, civil_rights, intellectuals, artists, athletes

FIGURES = [
    # ===== QUEENS =====
    {"id": "hatshepsut", "name": "Hatshepsut", "category": "queens", "era": "r. 1479–1458 BCE", "region": "Ancient Egypt", "lifespan": "c. 1507–1458 BCE",
     "summary": "Female pharaoh of the 18th Dynasty who launched a great trading expedition to Punt and built the mortuary temple of Deir el-Bahari, one of the architectural masterpieces of antiquity.",
     "story": "Hatshepsut assumed the full titulary of a pharaoh, was depicted in male regalia and with a ceremonial beard. Her 22-year reign was peaceful and prosperous. After her death her successor Thutmose III attempted to erase her monuments — a process scholars now read less as personal vendetta than as a dynastic clarification.",
     "legacy": "Among the most successful pharaohs by any measure. Her temple at Deir el-Bahari and her Punt reliefs remain primary sources for Bronze Age trade.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
     "sources": ["Joyce Tyldesley, 'Hatchepsut' (1996)"]},
    {"id": "cleopatra", "name": "Cleopatra VII", "category": "queens", "era": "r. 51–30 BCE", "region": "Ptolemaic Egypt", "lifespan": "69–30 BCE",
     "summary": "Last active ruler of the Ptolemaic Kingdom of Egypt, a Macedonian-descended dynasty long settled in Alexandria. Famed polyglot, naval commander, and ally of Julius Caesar and Mark Antony.",
     "story": "Cleopatra was reportedly the first Ptolemaic ruler to learn the Egyptian language. Her political and military partnership with Rome — first Caesar, then Antony — sought to preserve Egyptian independence; defeat at Actium in 31 BCE ended both her reign and Hellenistic Egypt.",
     "legacy": "A figure of enduring myth in Roman, Arabic, and European literature; recent scholarship emphasizes her statecraft over the romantic legend.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
     "sources": ["Plutarch, 'Life of Antony'", "Duane W. Roller, 'Cleopatra' (2010)"]},
    {"id": "amanirenas", "name": "Amanirenas", "category": "queens", "era": "r. c. 40–10 BCE", "region": "Kush (Meroë)", "lifespan": "c. 60–10 BCE",
     "summary": "Kandake (warrior queen) of Kush who fought Augustan Rome to a negotiated peace — one of the few rulers to do so on favorable terms.",
     "story": "Around 24 BCE she led an army that sacked Roman Aswan and toppled statues of Augustus (a bronze head later found buried under the steps of a Meroitic temple at Meroë is now in the British Museum). Negotiations at Samos in 21 BCE produced a treaty highly favorable to Kush.",
     "legacy": "Treaty terms were respected for nearly three centuries — an exceptional outcome against Rome at its imperial zenith.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
     "sources": ["Strabo, Geography 17.1.54", "László Török, 'The Kingdom of Kush' (1997)"]},
    {"id": "nzinga", "name": "Queen Nzinga of Ndongo and Matamba", "category": "queens", "era": "r. 1624–1663", "region": "Angola (Mbundu)", "lifespan": "1583–1663",
     "summary": "Mbundu queen who fought a 30-year campaign against the Portuguese, expertly using diplomacy, military innovation, and shifting alliances to preserve sovereign space in Central Africa.",
     "story": "She negotiated with the Portuguese governor in 1622 from a position of dignity (the famous account in which she refused to sit on the floor by sitting on the back of a kneeling attendant). She allied with the Dutch when it was useful and converted to Christianity when it served her diplomacy.",
     "legacy": "National hero of Angola; one of the most studied African political minds of the early modern period.",
     "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Linda Heywood, 'Njinga of Angola' (2017)"]},
    {"id": "yaa-asantewaa", "name": "Yaa Asantewaa", "category": "queens", "era": "1840–1921", "region": "Asante (Ghana)", "lifespan": "1840–1921",
     "summary": "Queen mother of Ejisu who led the 1900 War of the Golden Stool against British colonial forces — the last major Asante uprising.",
     "story": "When the British governor demanded the Golden Stool — the soul of the Asante nation — Yaa Asantewaa addressed the chiefs: 'If you the men of Asante will not go forward, then we will. We will fight the white men until the last of us falls.' She led a six-month siege of the British fort at Kumasi.",
     "legacy": "Captured and exiled to Seychelles, where she died in 1921. National hero of Ghana; her memory shaped Pan-African feminism.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["A. Adu Boahen, 'Yaa Asantewaa' (2003)"]},
    {"id": "amina", "name": "Queen Amina of Zazzau", "category": "queens", "era": "late 16th c.", "region": "Hausa (northern Nigeria)", "lifespan": "c. 1533–1610",
     "summary": "Warrior queen of the Hausa city-state of Zazzau (Zaria) who expanded its trade reach across the Sahel and built the city's famous defensive walls.",
     "story": "Praised in the Kano Chronicle as a queen 'as capable as a man', Amina led 34 years of military campaigns that opened trade routes from the Niger to the Atlantic. The earthen ramparts known as 'ganuwar Amina' (Amina's walls) survive in fragments around several Hausa cities.",
     "legacy": "A defining figure of Hausa historical memory; the subject of contemporary biography, fiction, and film.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["The Kano Chronicle", "Abdullahi Smith (ed.), 'A Little New Light' (1987)"]},
    {"id": "makeda", "name": "Makeda (Queen of Sheba)", "category": "queens", "era": "10th c. BCE (traditional)", "region": "Ethiopia / Yemen",
     "summary": "Legendary queen attested in Hebrew, Arabic, and Ethiopian traditions. The Kebra Nagast names her Makeda and makes her the foundational ancestor of the Solomonic dynasty of Ethiopia through her son Menelik I.",
     "story": "Her visit to King Solomon of Jerusalem is recounted in 1 Kings 10 and 2 Chronicles 9. The Ethiopian Kebra Nagast (14th c.) elaborates this as the origin of Ethiopian kingship and the carrying of the Ark of the Covenant to Aksum.",
     "legacy": "Foundational to the Solomonic dynasty's legitimacy through to Emperor Haile Selassie (1930–1974).",
     "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Kebra Nagast (Ethiopic, 14th c.)", "1 Kings 10"]},
    {"id": "ranavalona", "name": "Ranavalona I of Madagascar", "category": "queens", "era": "r. 1828–1861", "region": "Madagascar", "lifespan": "c. 1788–1861",
     "summary": "Sovereign of the Kingdom of Madagascar who, through an isolationist policy and military reforms, kept Madagascar independent of Britain and France for a generation when most of the world's coastlines were being colonized.",
     "story": "Her reign saw the construction of the Rova of Antananarivo and a state-led industrialization program led by the Frenchman Jean Laborde. European accounts vilified her; modern scholarship reassesses her as a strategic anti-colonial ruler.",
     "legacy": "Madagascar remained sovereign until 1896 — uniquely late for the era.",
     "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Stephen Ellis, 'The Rising of the Red Shawls' (1985)"]},

    # ===== KINGS / EMPERORS =====
    {"id": "mansa-musa", "name": "Mansa Musa", "category": "kings", "era": "r. 1312–1337", "region": "Mali Empire",
     "summary": "Tenth Mansa of Mali, whose pilgrimage to Mecca in 1324 is the most documented African royal journey of the medieval era. Modern estimates make him among the wealthiest individuals in recorded history.",
     "story": "His caravan brought so much gold to Cairo that contemporary observers reported the value of the dinar fell for years. He returned with the Andalusian architect al-Sahili and inaugurated the great period of Timbuktu's scholarship.",
     "legacy": "Depicted on the 1375 Catalan Atlas holding a golden nugget — Mali's place in the medieval world imagination.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["al-Umari", "Ibn Khaldun, Muqaddimah"]},
    {"id": "sundiata", "name": "Sundiata Keita", "category": "kings", "era": "r. c. 1235–1255", "region": "Mali Empire",
     "summary": "Founder of the Mali Empire; the central figure of the Sundiata epic preserved by Mande griots.",
     "story": "Born to the Mandinka chief Naré Maghan, he was sent into exile, returned to defeat the sorcerer-king Sumanguru Kanté of the Sosso at the Battle of Kirina (c. 1235), and convened the Gbara assembly that issued the Kouroukan Fouga — among the earliest known charters of customary rights in West Africa.",
     "legacy": "The Sundiata epic remains an oral and now written cornerstone of West African literature.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["D. T. Niane, 'Sundiata: An Epic of Old Mali' (1960)"]},
    {"id": "shaka", "name": "Shaka kaSenzangakhona", "category": "kings", "era": "r. 1816–1828", "region": "Zulu Kingdom",
     "summary": "Founding king of the Zulu Kingdom whose military reforms reshaped southern Africa during the Mfecane.",
     "story": "He reorganized the Nguni age-regiment system into a standing army, introduced the short stabbing iklwa, and the encircling 'horns of the buffalo' formation. The polity he built defeated the British at Isandlwana fifty years after his assassination.",
     "legacy": "Subject of an enormous body of historical scholarship and contested oral tradition. National figure of South Africa.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["John Laband, 'Rope of Sand' (1995)"]},
    {"id": "taharqa", "name": "Taharqa", "category": "kings", "era": "r. 690–664 BCE", "region": "Kush / Egypt (25th Dynasty)",
     "summary": "Nubian pharaoh of Egypt and Kush whose building program included pyramids at Nuri and temples at Karnak.",
     "story": "Ruled an empire stretching from the Mediterranean to the upper Nile. He clashed with Assyrian kings Sennacherib and Esarhaddon — referenced in the Hebrew Bible (2 Kings 19:9) as 'Tirhakah, king of Cush'.",
     "legacy": "The 25th Dynasty restored monumental building in Egypt after a period of decline.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
     "sources": ["Robert Morkot, 'The Black Pharaohs' (2000)"]},
    {"id": "haile-selassie", "name": "Haile Selassie I", "category": "kings", "era": "r. 1930–1974", "region": "Ethiopia", "lifespan": "1892–1975",
     "summary": "Last Emperor of Ethiopia and key 20th-century figure of Pan-Africanism and decolonization.",
     "story": "His 1936 League of Nations address pleading for collective action against Italian invasion is one of the great moral speeches of the century. He led Ethiopia's restoration after the Italian occupation, co-founded the Organisation of African Unity in 1963, and was central to the Non-Aligned Movement.",
     "legacy": "Revered as the messiah of Rastafari faith. Deposed in 1974; the Ethiopian Empire ended with him.",
     "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Bahru Zewde, 'A History of Modern Ethiopia' (2001)"]},

    # ===== MILITARY / REVOLUTIONARIES =====
    {"id": "toussaint", "name": "Toussaint Louverture", "category": "military", "era": "1791–1803", "region": "Haiti (Saint-Domingue)", "lifespan": "c. 1743–1803",
     "summary": "Self-emancipated leader of the Haitian Revolution — the only successful slave revolution in history to found a sovereign state.",
     "story": "Born enslaved on the Bréda plantation, he led an army of formerly enslaved people that defeated French, Spanish, and British forces. He issued the 1801 constitution that abolished slavery permanently. Betrayed by Napoleon, he died in a French prison at Fort de Joux in 1803 — a year before Haitian independence.",
     "legacy": "Inspired abolitionist movements across the Atlantic; subject of C.L.R. James's 'The Black Jacobins'.",
     "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["C.L.R. James, 'The Black Jacobins' (1938)", "Laurent Dubois, 'Avengers of the New World' (2004)"]},
    {"id": "dessalines", "name": "Jean-Jacques Dessalines", "category": "military", "era": "1804–1806", "region": "Haiti", "lifespan": "1758–1806",
     "summary": "Founding emperor of independent Haiti; declared independence on 1 January 1804.",
     "story": "Lieutenant of Toussaint who finished the war Toussaint started. The Haitian declaration of independence stands as one of the most radical political documents of the early 19th century.",
     "legacy": "Father of Haitian independence; assassinated in 1806.",
     "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Julius Scott, 'The Common Wind' (2018)"]},
    {"id": "zumbi", "name": "Zumbi dos Palmares", "category": "military", "era": "1655–1695", "region": "Brazil (Palmares)",
     "summary": "Last king of the Quilombo dos Palmares, the largest maroon polity in the Americas, holding off Portuguese and Dutch attacks for nearly a century.",
     "story": "Born free in Palmares, captured young and raised by a Portuguese priest, he escaped at 15 to return to Palmares and led its final resistance. Palmares fell in 1694; Zumbi was killed in February 1695.",
     "legacy": "The 20 November anniversary of his death is Brazil's national Black Consciousness Day (Dia da Consciência Negra), a federal holiday from 2023.",
     "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Décio Freitas, 'Palmares: a guerra dos escravos' (1973)"]},
    {"id": "harriet-tubman", "name": "Harriet Tubman", "category": "military", "era": "1820s–1913", "region": "United States", "lifespan": "c. 1822–1913",
     "summary": "Underground Railroad conductor and Union Army scout — the only woman to lead an armed military expedition during the U.S. Civil War.",
     "story": "Escaped slavery in Maryland in 1849 and returned at least 13 times to free roughly 70 people. In 1863 she led the Combahee Ferry Raid in South Carolina, freeing more than 700 enslaved people in a single night.",
     "legacy": "First woman to lead a U.S. military operation; due to appear on the U.S. $20 bill.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Kate Larson, 'Bound for the Promised Land' (2004)"]},

    # ===== SCIENTISTS / INVENTORS =====
    {"id": "imhotep", "name": "Imhotep", "category": "scientists", "era": "27th c. BCE", "region": "Ancient Egypt",
     "summary": "Chancellor of Djoser, architect of the Step Pyramid at Saqqara — the first monumental stone building anywhere in the world — and revered in later antiquity as a god of medicine.",
     "story": "Identified as the architect of the Step Pyramid (c. 2670 BCE). The Edwin Smith Surgical Papyrus, which records empirical observation of trauma cases, is later but probably reflects a medical tradition associated with him.",
     "legacy": "One of the very few non-royal Egyptians to be deified; equated by the Greeks with Asclepius.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
     "sources": ["Miriam Lichtheim, 'Ancient Egyptian Literature'"]},
    {"id": "lewis-latimer", "name": "Lewis Latimer", "category": "inventors", "era": "1848–1928", "region": "United States",
     "summary": "African American inventor and patent draftsman who improved the carbon filament for the incandescent light bulb (patent 1881), enabling longer-lasting, mass-producible electric lighting.",
     "story": "Drafted the patent for Alexander Graham Bell's telephone. Worked with Hiram Maxim and later with Thomas Edison's company. Wrote one of the first textbooks on electrical lighting (1890).",
     "legacy": "His filament process made widespread electric lighting commercially viable.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Bayla Singer, 'Black Pioneers of Science and Invention'"]},
    {"id": "mark-dean", "name": "Mark Dean", "category": "inventors", "era": "b. 1957", "region": "United States",
     "summary": "American computer engineer who holds three of IBM's original nine patents for the PC and co-invented the color PC monitor and the first gigahertz processor.",
     "story": "Led the team behind the ISA bus that enabled add-on cards to talk to the CPU — the architecture that defined the PC era. First African American IBM Fellow (1995).",
     "legacy": "Inducted into the National Inventors Hall of Fame in 1997.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["IBM Archives", "NIHF citation"]},
    {"id": "katherine-johnson", "name": "Katherine Johnson", "category": "scientists", "era": "1918–2020", "region": "United States",
     "summary": "NASA mathematician whose trajectory calculations were essential to the success of the first U.S. crewed spaceflights, including John Glenn's 1962 orbital mission and the 1969 Apollo 11 lunar landing.",
     "story": "John Glenn famously refused to fly unless 'the girl' (Johnson) recalculated by hand the trajectories produced by NASA's IBM 7090. Worked at NASA from 1953 to 1986.",
     "legacy": "Presidential Medal of Freedom (2015); subject of 'Hidden Figures' (2016).",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Margot Lee Shetterly, 'Hidden Figures' (2016)"]},
    {"id": "percy-julian", "name": "Percy Lavon Julian", "category": "scientists", "era": "1899–1975", "region": "United States",
     "summary": "African American chemist whose synthesis of physostigmine (1935) and later cortisone from soybeans made glaucoma and arthritis treatments affordable.",
     "story": "Held more than 130 patents; founder of Julian Laboratories. Faced systematic exclusion from academic chemistry yet rose to lead industrial research.",
     "legacy": "National Inventors Hall of Fame (1990); commemorated on a U.S. postage stamp.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Bernhard Witkop, 'Percy Lavon Julian' (1980, biographical memoir)"]},

    # ===== CIVIL RIGHTS =====
    {"id": "mlk", "name": "Martin Luther King Jr.", "category": "civil_rights", "era": "1929–1968", "region": "United States",
     "summary": "Baptist minister and chief spokesperson of the African American civil rights movement from 1955 until his assassination in 1968.",
     "story": "Led the Montgomery bus boycott (1955–56), co-founded the Southern Christian Leadership Conference, delivered 'I Have a Dream' on the Mall in August 1963, won the Nobel Peace Prize in 1964, and helped achieve the Civil Rights Act (1964) and the Voting Rights Act (1965). Assassinated in Memphis, 4 April 1968.",
     "legacy": "U.S. federal holiday since 1986; a defining figure of 20th-century moral leadership.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Taylor Branch, 'Parting the Waters' (1988)"]},
    {"id": "rosa-parks", "name": "Rosa Parks", "category": "civil_rights", "era": "1913–2005", "region": "United States",
     "summary": "Activist whose December 1955 refusal to surrender her seat on a Montgomery bus catalyzed the 13-month bus boycott that propelled the U.S. civil rights movement.",
     "story": "A long-time NAACP secretary who had trained at the Highlander Folk School, Parks was no spontaneous protester — she was an experienced organizer. Her case became a federal test of segregation laws.",
     "legacy": "First woman to lie in honor in the U.S. Capitol Rotunda (2005); Congressional Gold Medal recipient.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Jeanne Theoharis, 'The Rebellious Life of Mrs. Rosa Parks' (2013)"]},
    {"id": "mandela", "name": "Nelson Mandela", "category": "civil_rights", "era": "1918–2013", "region": "South Africa",
     "summary": "Anti-apartheid leader, first president of post-apartheid South Africa (1994–1999), Nobel Peace laureate (1993).",
     "story": "Co-founder of the ANC Youth League and the armed wing Umkhonto we Sizwe; sentenced to life at the Rivonia Trial in 1964 and imprisoned for 27 years (Robben Island, Pollsmoor, Victor Verster). Released in 1990. Negotiated the peaceful end of apartheid with F. W. de Klerk.",
     "legacy": "Iconic symbol of reconciliation; the 18 July international Nelson Mandela Day is a UN-recognized observance.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Nelson Mandela, 'Long Walk to Freedom' (1994)"]},
    {"id": "malcolm-x", "name": "Malcolm X", "category": "civil_rights", "era": "1925–1965", "region": "United States",
     "summary": "Minister, human-rights activist, and major theorist of Black self-determination in the 20th century.",
     "story": "Rose as the leading public voice of the Nation of Islam; broke with it in 1964, made the Hajj, embraced orthodox Sunni Islam, and founded the Organization of Afro-American Unity. Assassinated 21 February 1965 at the Audubon Ballroom in Harlem.",
     "legacy": "'The Autobiography of Malcolm X' (with Alex Haley, 1965) reshaped American political thought.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Manning Marable, 'Malcolm X: A Life of Reinvention' (2011)"]},
    {"id": "marcus-garvey", "name": "Marcus Garvey", "category": "civil_rights", "era": "1887–1940", "region": "Jamaica / United States",
     "summary": "Founder of the Universal Negro Improvement Association (UNIA, 1914) — the largest mass movement of African-descended people in history.",
     "story": "Garveyism (Black pride, economic self-reliance, return-to-Africa) reached millions across the Americas, Caribbean, and Africa. He founded the Black Star Line shipping company. His thinking shaped Nkrumah, Kenyatta, and Rastafari.",
     "legacy": "Jamaica's first national hero (1969). Considered the father of Pan-Africanism as a mass movement.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Colin Grant, 'Negro with a Hat' (2008)"]},
    {"id": "frederick-douglass", "name": "Frederick Douglass", "category": "civil_rights", "era": "1818–1895", "region": "United States",
     "summary": "Self-emancipated orator, writer, and statesman — the most photographed American of the 19th century.",
     "story": "Born enslaved in Maryland; escaped in 1838. His 1845 'Narrative' and two later autobiographies are foundational American literature. Counseled President Lincoln during the Civil War; served as U.S. ambassador to Haiti.",
     "legacy": "His 1852 speech 'What to the Slave is the Fourth of July?' remains one of the great works of American political rhetoric.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["David Blight, 'Frederick Douglass: Prophet of Freedom' (2018)"]},

    # ===== INTELLECTUALS / WRITERS =====
    {"id": "du-bois", "name": "W.E.B. Du Bois", "category": "intellectuals", "era": "1868–1963", "region": "United States",
     "summary": "Sociologist, historian, and civil-rights pioneer; co-founder of the NAACP (1909); first African American to receive a Harvard PhD.",
     "story": "His 'The Souls of Black Folk' (1903) introduced 'double consciousness' as an analytic of Black American life. He organized five Pan-African Congresses between 1919 and 1945, ending in Manchester with Nkrumah, Kenyatta, and Padmore.",
     "legacy": "Died in Ghana on the eve of the 1963 March on Washington.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["David Levering Lewis, 'W.E.B. Du Bois' (1993, 2000) — two-volume biography (Pulitzer Prize)"]},
    {"id": "fanon", "name": "Frantz Fanon", "category": "intellectuals", "era": "1925–1961", "region": "Martinique / Algeria",
     "summary": "Psychiatrist and revolutionary theorist whose 'Black Skin, White Masks' (1952) and 'The Wretched of the Earth' (1961) reshaped postcolonial thought.",
     "story": "Trained as a psychiatrist in Lyon, posted to Blida-Joinville in Algeria, he joined the FLN during the Algerian War of Independence. Wrote 'The Wretched of the Earth' while dying of leukemia at 36.",
     "legacy": "Founding text of postcolonial theory; influence runs through Édouard Glissant, Stuart Hall, and contemporary critical theory.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["David Macey, 'Frantz Fanon: A Biography' (2000)"]},
    {"id": "achebe", "name": "Chinua Achebe", "category": "intellectuals", "era": "1930–2013", "region": "Nigeria",
     "summary": "Nigerian novelist whose 'Things Fall Apart' (1958) is among the most translated and taught African novels in history.",
     "story": "Igbo writer who reframed how African societies could be written about in fiction. His later essays — notably the 1975 lecture on Conrad's 'Heart of Darkness' — reshaped postcolonial literary criticism.",
     "legacy": "Often called 'the father of modern African literature'. Inspired generations of African writers from Ngũgĩ wa Thiong'o to Chimamanda Ngozi Adichie.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Ezenwa-Ohaeto, 'Chinua Achebe: A Biography' (1997)"]},
    {"id": "morrison", "name": "Toni Morrison", "category": "intellectuals", "era": "1931–2019", "region": "United States",
     "summary": "Novelist, editor, and essayist; first African American woman to win the Nobel Prize in Literature (1993).",
     "story": "As an editor at Random House she championed Toni Cade Bambara, Gayl Jones, and Angela Davis. Her novels — 'Beloved' (1987, Pulitzer), 'Song of Solomon', 'Sula' — remade the American novel.",
     "legacy": "Presidential Medal of Freedom (2012); foundational to contemporary literature.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Lynn Orilla Scott, 'Toni Morrison: A Biography' (2020)"]},

    # ===== ARTS / MUSIC =====
    {"id": "louis-armstrong", "name": "Louis Armstrong", "category": "artists", "era": "1901–1971", "region": "United States",
     "summary": "Trumpeter, vocalist, and the single most influential musician in the development of jazz.",
     "story": "Born in New Orleans, came up under King Oliver, recorded the Hot Five and Hot Seven sessions (1925–28) that defined the jazz solo. The first internationally famous African American entertainer and a U.S. cultural ambassador to dozens of countries.",
     "legacy": "Reshaped popular singing as well as instrumental music; his style underlies a century of vocal phrasing.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Terry Teachout, 'Pops' (2009)"]},
    {"id": "fela", "name": "Fela Anikulapo Kuti", "category": "artists", "era": "1938–1997", "region": "Nigeria",
     "summary": "Nigerian multi-instrumentalist, bandleader, and inventor of Afrobeat — a fusion of West African rhythm, jazz, funk, and political consciousness.",
     "story": "Founded the Kalakuta Republic commune in Lagos, opposing successive military governments. His 1977 album 'Zombie' so provoked the regime that the army burned Kalakuta and threw his mother from a window. He fought on with music until his death.",
     "legacy": "Father of Afrobeat; godfather of contemporary Afrobeats.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Carlos Moore, 'Fela: This Bitch of a Life' (1982)"]},
    {"id": "miriam-makeba", "name": "Miriam Makeba", "category": "artists", "era": "1932–2008", "region": "South Africa",
     "summary": "Singer and anti-apartheid activist known globally as 'Mama Africa'.",
     "story": "Driven into 30-year exile after testifying against apartheid at the UN in 1963. Hits like 'Pata Pata' (1967) made Xhosa music a global sound. Married Stokely Carmichael and continued activism across continents.",
     "legacy": "Recipient of the Polar Music Prize (2001); central figure in the Afro-political music of the 20th century.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Miriam Makeba, 'Makeba: My Story' (1987)"]},

    # ===== ATHLETES =====
    {"id": "muhammad-ali", "name": "Muhammad Ali", "category": "athletes", "era": "1942–2016", "region": "United States",
     "summary": "Three-time heavyweight boxing world champion; refused induction into the U.S. military in 1967 in opposition to the Vietnam War, sacrificing the prime of his career on principle.",
     "story": "Won Olympic gold in Rome 1960. Conversion to the Nation of Islam in 1964. The 'Rumble in the Jungle' against George Foreman in Kinshasa (1974) and the 'Thrilla in Manila' against Joe Frazier (1975) became defining sports events of the century.",
     "legacy": "Presidential Medal of Freedom (2005); his stand against the draft became a global symbol of moral conviction.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Jonathan Eig, 'Ali: A Life' (2017)"]},
    {"id": "jesse-owens", "name": "Jesse Owens", "category": "athletes", "era": "1913–1980", "region": "United States",
     "summary": "Sprinter and long jumper who won four gold medals at the 1936 Berlin Olympics — directly refuting Nazi racial ideology before the world's largest stage.",
     "story": "Within 45 minutes at a Big Ten meet in 1935 he tied a world record and set three more — long considered the greatest single hour in track and field. In Berlin 1936 he won the 100m, 200m, long jump, and 4x100m relay.",
     "legacy": "Presidential Medal of Freedom (1976); Congressional Gold Medal (1990).",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Jeremy Schaap, 'Triumph' (2007)"]},

    # ===== ADDITIONAL FIGURES =====
    {"id": "lumumba", "name": "Patrice Lumumba", "category": "civil_rights", "era": "1925–1961", "region": "Congo (DRC)",
     "summary": "First Prime Minister of the independent Democratic Republic of the Congo (June 1960); a defining voice of African independence.",
     "story": "His 30 June 1960 independence-day speech, delivered in the presence of the Belgian king, named colonial violence directly and reframed the moment. Within months he was deposed in a CIA- and Belgian-backed coup and assassinated in January 1961 in Katanga.",
     "legacy": "Belgium officially apologized for its role in 2002; his single tooth, the only physical remains, was returned to Congo in 2022.",
     "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Ludo De Witte, 'The Assassination of Lumumba' (2001)"]},
    {"id": "sankara", "name": "Thomas Sankara", "category": "civil_rights", "era": "1949–1987", "region": "Burkina Faso",
     "summary": "Pan-Africanist and Marxist revolutionary; President of Burkina Faso (1983–1987) who renamed the country from 'Upper Volta' to 'Land of the Upright People'.",
     "story": "In four years his government cut child mortality, planted 10 million trees against desertification, banned female genital cutting and forced marriage, and refused IMF loan conditions. Assassinated 15 October 1987 in a coup led by his comrade Blaise Compaoré.",
     "legacy": "'Africa's Che Guevara'; rehabilitated by Burkina Faso as national hero; the trial of his assassins concluded in 2022.",
     "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Ernest Harsch, 'Thomas Sankara: An African Revolutionary' (2014)"]},
    {"id": "nkrumah", "name": "Kwame Nkrumah", "category": "civil_rights", "era": "1909–1972", "region": "Ghana",
     "summary": "Leader of Ghana's independence (1957) — the first sub-Saharan African colony to break free of European rule — and chief architect of the Pan-African movement of the 20th century.",
     "story": "Trained in the United States and Britain, organized the 5th Pan-African Congress (Manchester 1945) with Du Bois and Padmore. Founded the Organisation of African Unity in 1963. Deposed in a 1966 coup while in Beijing.",
     "legacy": "His 1957 declaration that 'Ghana's independence is meaningless unless it is linked with the total liberation of the African continent' set the agenda for the era.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["David Birmingham, 'Kwame Nkrumah: The Father of African Nationalism' (1998)"]},
    {"id": "biko", "name": "Steve Biko", "category": "civil_rights", "era": "1946–1977", "region": "South Africa",
     "summary": "Founder of the South African Students' Organisation and intellectual architect of the Black Consciousness Movement.",
     "story": "His writings (collected in 'I Write What I Like') reshaped anti-apartheid thought in the 1970s. Detained without charge under the Terrorism Act, he was tortured to death in police custody on 12 September 1977.",
     "legacy": "His death became a turning point in international pressure on apartheid; the 1987 film 'Cry Freedom' brought his story to a global audience.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Steve Biko, 'I Write What I Like' (1978)"]},
    {"id": "angela-davis", "name": "Angela Davis", "category": "intellectuals", "era": "b. 1944", "region": "United States",
     "summary": "Philosopher, abolitionist, and activist; central figure in the U.S. prison-abolition movement and feminist theory.",
     "story": "Studied with Marcuse and Adorno. Acquitted in a 1972 trial that drew global solidarity ('Free Angela' was painted on walls from Paris to Moscow). Co-founded Critical Resistance (1997).",
     "legacy": "Her 'Women, Race & Class' (1981) and 'Are Prisons Obsolete?' (2003) are core texts of contemporary critical theory.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Angela Y. Davis, 'An Autobiography' (1974, 2022)"]},
    {"id": "maya-angelou", "name": "Maya Angelou", "category": "intellectuals", "era": "1928–2014", "region": "United States",
     "summary": "Poet, memoirist, and civil-rights organizer. Her 'I Know Why the Caged Bird Sings' (1969) was the first widely read autobiography by a contemporary African American woman.",
     "story": "Worked with Martin Luther King Jr. and Malcolm X; lived in Egypt and Ghana in the early 1960s. Recited 'On the Pulse of Morning' at Bill Clinton's 1993 inauguration.",
     "legacy": "Presidential Medal of Freedom (2011); subject of countless biographies.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Maya Angelou, 'I Know Why the Caged Bird Sings' (1969)"]},
    {"id": "wangari", "name": "Wangari Maathai", "category": "intellectuals", "era": "1940–2011", "region": "Kenya",
     "summary": "Environmentalist and political activist; first African woman to receive the Nobel Peace Prize (2004) for her work with the Green Belt Movement.",
     "story": "Founded the Green Belt Movement in 1977; the movement planted more than 51 million trees across Kenya and trained 30,000 women in forestry, food processing, and bee-keeping. First woman in East and Central Africa to earn a doctorate (Veterinary Anatomy, 1971).",
     "legacy": "Transformed how environmentalism is understood in the global South; her autobiography 'Unbowed' (2006) is read worldwide.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Wangari Maathai, 'Unbowed' (2006)"]},
    {"id": "bob-marley", "name": "Bob Marley", "category": "artists", "era": "1945–1981", "region": "Jamaica",
     "summary": "Singer, songwriter, and Rastafari ambassador who took reggae from Trench Town to a global audience.",
     "story": "With the Wailers (Peter Tosh, Bunny Wailer) he made a music of resistance, mysticism, and joy. The 'One Love Peace Concert' (1978) in Kingston brought rival political leaders Michael Manley and Edward Seaga onto the same stage. Album 'Exodus' (1977) was named TIME album of the 20th century.",
     "legacy": "Order of Merit of Jamaica; his recordings remain bestselling globally four decades after his death.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Timothy White, 'Catch a Fire' (1983)"]},
    {"id": "aretha", "name": "Aretha Franklin", "category": "artists", "era": "1942–2018", "region": "United States",
     "summary": "Singer and pianist; 'The Queen of Soul'. First woman inducted into the Rock & Roll Hall of Fame (1987).",
     "story": "Daughter of the prominent Detroit preacher C. L. Franklin. Her 1967 Atlantic recordings — 'Respect', 'Natural Woman', 'Chain of Fools' — defined American popular music. Sang at the inaugurations of Carter, Clinton, and Obama, and at MLK's funeral.",
     "legacy": "Presidential Medal of Freedom (2005); voice of the civil-rights generation.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["David Ritz, 'Respect: The Life of Aretha Franklin' (2014)"]},
    {"id": "garrett-morgan", "name": "Garrett Morgan", "category": "inventors", "era": "1877–1963", "region": "United States",
     "summary": "African American inventor of the three-position traffic signal (1923) and an early respiratory safety hood — the prototype of the modern gas mask.",
     "story": "His safety hood, patented 1914, was used heroically in 1916 during the Cleveland Waterworks disaster to rescue trapped workers. His traffic-signal patent was sold to General Electric for $40,000 — a sum equivalent to roughly $700,000 today.",
     "legacy": "Two foundational safety inventions of the 20th century.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Garrett A. Morgan Papers, Western Reserve Historical Society"]},

    # ===== WOMEN SCIENTISTS / INVENTORS =====
    {"id": "alice-ball", "name": "Alice Ball", "category": "scientists", "era": "1892–1916", "region": "United States",
     "summary": "Chemist who at age 23 developed the first effective injectable treatment for leprosy (Hansen's disease) — the 'Ball Method' that remained the standard of care into the 1940s.",
     "story": "Earned a master's in chemistry from the College of Hawaiʻi (1915) — the first woman and first African American to do so. Isolated the active esters of chaulmoogra oil; her injectable form treated thousands at the Kalaupapa settlement. She died at 24; her colleague Arthur Dean published her method without credit. The University of Hawaiʻi formally acknowledged her work in 2000.",
     "legacy": "Hawaiʻi designated 29 February 'Alice Ball Day' in 2000.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["University of Hawaiʻi Archives", "Paul Wermager, 'Alice Ball'"]},
    {"id": "marie-daly", "name": "Marie Maynard Daly", "category": "scientists", "era": "1921–2003", "region": "United States",
     "summary": "First African American woman to earn a PhD in chemistry (Columbia, 1947); pioneering biochemist whose research linked cholesterol and hypertension to heart disease.",
     "story": "At Rockefeller Institute and Columbia, she identified how cholesterol clogs arteries — work that underpins modern cardiology. Co-founded a scholarship for minority students in science.",
     "legacy": "Subject of the AAAS Marie Maynard Daly Award; her research changed cardiovascular medicine.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Wini Warren, 'Black Women Scientists in the United States' (1999)"]},
    {"id": "patricia-bath", "name": "Patricia Bath", "category": "inventors", "era": "1942–2019", "region": "United States",
     "summary": "Ophthalmologist who invented the Laserphaco Probe (patented 1988) — a laser device that revolutionized cataract surgery and restored sight to people blind for decades.",
     "story": "First African American woman to complete an ophthalmology residency (NYU, 1973), to lead a postgraduate medical training program in the US, and to receive a medical patent. Co-founder of the American Institute for the Prevention of Blindness.",
     "legacy": "National Inventors Hall of Fame (2022); her device is in use worldwide.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["NIH Changing the Face of Medicine"]},
    {"id": "mae-jemison", "name": "Mae Jemison", "category": "scientists", "era": "b. 1956", "region": "United States",
     "summary": "Engineer, physician, and the first African American woman in space — flew aboard Space Shuttle Endeavour on STS-47 (1992).",
     "story": "Stanford engineering at 16, Cornell MD, Peace Corps medical officer in Sierra Leone and Liberia before joining NASA. Now leads the 100 Year Starship initiative aimed at making interstellar travel possible within 100 years.",
     "legacy": "International Space Hall of Fame; Texas Medical Center Hall of Fame.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Mae Jemison, 'Find Where the Wind Goes' (2001)"]},
    {"id": "bessie-coleman", "name": "Bessie Coleman", "category": "athletes", "era": "1892–1926", "region": "United States",
     "summary": "First African American and first Native American woman to hold a pilot's license — earned in France in 1921 because no US flight school would admit her.",
     "story": "Refused by every American flight school, she learned French and trained at the Caudron Brothers School in Le Crotoy. Returned to barnstorm across the United States, refusing to perform at venues that excluded Black audiences. Died at 34 in an aircraft preparation accident.",
     "legacy": "U.S. Postal Service stamp (1995); Bessie Coleman Aviators Club continues her work.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Doris Rich, 'Queen Bess: Daredevil Aviator' (1993)"]},
    {"id": "henrietta-lacks", "name": "Henrietta Lacks", "category": "scientists", "era": "1920–1951", "region": "United States",
     "summary": "African American woman whose cervical cancer cells (HeLa, taken without her knowledge in 1951) became the first immortal human cell line — the foundation of modern biomedical research.",
     "story": "HeLa cells enabled the polio vaccine, in-vitro fertilization, the human genome project, cancer research, and COVID-19 vaccine development. Her family was not informed for 25 years and saw no compensation. In 2023 the Lacks estate settled with biotech firm Thermo Fisher.",
     "legacy": "Posthumous Presidential Medal of Freedom (2024); Rebecca Skloot's 'The Immortal Life of Henrietta Lacks' (2010) brought her story to global attention.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Rebecca Skloot, 'The Immortal Life of Henrietta Lacks' (2010)"]},

    # ===== FRANCOPHONE AFRICA & DIASPORA =====
    {"id": "senghor", "name": "Léopold Sédar Senghor", "category": "intellectuals", "era": "1906–2001", "region": "Senegal",
     "summary": "Poet and statesman; first President of independent Senegal (1960–1980); co-founder with Aimé Césaire and Léon-Gontran Damas of the négritude movement in 1930s Paris.",
     "story": "First African elected to the Académie française (1983). Voluntarily stepped down from power in 1980 — extraordinarily rare for African leaders of his generation. His poetry ('Chants d'ombre', 'Hosties noires') reframed Black identity in French letters.",
     "legacy": "Founding voice of francophone African literature.",
     "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
     "sources": ["Janet Vaillant, 'Black, French, and African' (1990)"]},
    {"id": "cesaire", "name": "Aimé Césaire", "category": "intellectuals", "era": "1913–2008", "region": "Martinique",
     "summary": "Poet, playwright, and politician; coined the term négritude. His 'Cahier d'un retour au pays natal' (1939) is among the most influential anti-colonial poems of the 20th century.",
     "story": "Mayor of Fort-de-France for 56 years (1945–2001), deputy to the French National Assembly for 48 years. Mentor of Frantz Fanon. His 'Discourse on Colonialism' (1950) named European colonialism a barbarism on par with fascism.",
     "legacy": "His complete works are taught across the Francophone world.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Gregson Davis, 'Aimé Césaire' (1997)"]},
    {"id": "damas", "name": "Léon-Gontran Damas", "category": "intellectuals", "era": "1912–1978", "region": "French Guiana",
     "summary": "Co-founder of négritude alongside Césaire and Senghor; his collection 'Pigments' (1937) was seized by the French colonial administration as 'a threat to State security'.",
     "story": "Born in Cayenne, French Guiana, of mixed African, Indigenous, and European descent. Edited 'L'Étudiant noir' in Paris in 1935. Sat in the French National Assembly (1948–1951). His poetry's biting rhythm shaped a generation.",
     "legacy": "Without him there is no négritude; recent scholarship has restored his place beside the two more famous co-founders.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Brent Hayes Edwards, 'The Practice of Diaspora' (2003)"]},
    {"id": "cheikh-anta-diop", "name": "Cheikh Anta Diop", "category": "intellectuals", "era": "1923–1986", "region": "Senegal",
     "summary": "Senegalese historian, anthropologist, and physicist who argued in 'Nations nègres et culture' (1954) for the African origin of ancient Egyptian civilization.",
     "story": "Doctoral thesis at the Sorbonne (defended 1960 on his fourth submission). Founded the radiocarbon-dating laboratory at IFAN in Dakar. Was a leading voice at the 1974 UNESCO Cairo Symposium on the peopling of ancient Egypt — a debate that reshaped Egyptology.",
     "legacy": "Université Cheikh Anta Diop in Dakar bears his name; central reference for Afrocentric scholarship.",
     "image_url": "https://images.unsplash.com/photo-1732027198030-d9ead6d14d4f?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Cheikh Anta Diop, 'The African Origin of Civilization' (1974 trans.)"]},
    {"id": "mariama-ba", "name": "Mariama Bâ", "category": "intellectuals", "era": "1929–1981", "region": "Senegal",
     "summary": "Senegalese novelist; her 1979 epistolary novel 'Une si longue lettre' is the most influential francophone African novel by a woman.",
     "story": "Trained as a teacher, raised nine children, married politician Obèye Diop and divorced him. Won the inaugural Noma Prize for Publishing in Africa (1980). Died of cancer the year her second novel 'Un chant écarlate' was published posthumously.",
     "legacy": "'Une si longue lettre' is translated into 25+ languages and taught worldwide.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Florence Stratton, 'Contemporary African Literature and the Politics of Gender' (1994)"]},
    {"id": "sembene", "name": "Ousmane Sembène", "category": "artists", "era": "1923–2007", "region": "Senegal",
     "summary": "Novelist and filmmaker often called the 'father of African cinema'; his 'La Noire de…' (1966) was the first feature-length film by a sub-Saharan African director released theatrically.",
     "story": "Self-taught dockworker turned writer; studied filmmaking in Moscow under Sergei Gerasimov. His films — 'Mandabi' (1968, first feature in Wolof), 'Xala' (1975), 'Camp de Thiaroye' (1988), 'Moolaadé' (2004) — combined Marxist politics, African languages, and devastating wit.",
     "legacy": "Founded modern African cinema; jury president at Cannes 1981.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Samba Gadjigo, 'Ousmane Sembène: The Making of a Militant Artist' (2010)"]},

    # ===== CARIBBEAN REVOLUTIONARIES =====
    {"id": "boukman", "name": "Dutty Boukman", "category": "military", "era": "?–1791", "region": "Haiti",
     "summary": "Vodou houngan whose 14 August 1791 ceremony at Bois Caïman is traditionally considered the spark of the Haitian Revolution.",
     "story": "Jamaican-born, sold to Saint-Domingue, became a leader of escaped self-emancipated communities. The Bois Caïman ceremony, presided over with the priestess Cécile Fatiman, sealed the oath that launched the August 22 uprising. Killed in battle in November 1791.",
     "legacy": "Founding figure of Haitian national memory.",
     "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Laurent Dubois, 'Avengers of the New World' (2004)"]},
    {"id": "cecile-fatiman", "name": "Cécile Fatiman", "category": "military", "era": "c. 1771–1883", "region": "Haiti",
     "summary": "Vodou priestess (manbo) who, with Boukman, led the Bois Caïman ceremony of 14 August 1791 — and lived to see Haitian independence and well into the era of the Republic.",
     "story": "Reportedly the daughter of an enslaved Mandingo woman and a Corsican prince. At Bois Caïman she sacrificed a black pig and led the assembled in their oath. Married revolutionary general Jean-Louis Pierrot, briefly president of Haiti in 1845.",
     "legacy": "One of the named women of the Haitian Revolution; her longevity made her a living monument of the revolution.",
     "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Carolyn Fick, 'The Making of Haiti' (1990)"]},
    {"id": "solitude", "name": "La Mulâtresse Solitude", "category": "military", "era": "c. 1772–1802", "region": "Guadeloupe",
     "summary": "Guadeloupean resistance leader who, while pregnant, fought Napoleon's reimposition of slavery in 1802 and was executed the day after she gave birth.",
     "story": "Born to a captured African woman raped during the Middle Passage. Joined Louis Delgrès's resistance against the 1802 French expedition that reinstated slavery in Guadeloupe. Delgrès and 400 of his followers chose mass suicide rather than surrender on 28 May 1802. Captured pregnant, Solitude was hanged on 29 November after the birth of her child, who was sold into slavery.",
     "legacy": "Statue in Pointe-à-Pitre and in Paris (Jardin du Luxembourg, 2022).",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["André Schwarz-Bart, 'La Mulâtresse Solitude' (1972)"]},
    {"id": "nanny", "name": "Queen Nanny of the Maroons", "category": "military", "era": "c. 1686–c. 1755", "region": "Jamaica",
     "summary": "Founder and military leader of the Windward Maroons of Jamaica; signed the 1739 treaty with the British that secured maroon autonomy.",
     "story": "Born in present-day Ghana, brought to Jamaica as a captive; escaped to the Blue Mountains and founded Nanny Town. For more than a decade she fought guerrilla campaigns against British colonial forces, freeing an estimated 800 enslaved people from plantations.",
     "legacy": "One of Jamaica's seven National Heroes (the only woman); her face appears on the J$500 bill.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Karla Gottlieb, 'The Mother of Us All' (2000)"]},
    {"id": "maceo", "name": "Antonio Maceo Grajales", "category": "military", "era": "1845–1896", "region": "Cuba",
     "summary": "Afro-Cuban general known as the 'Bronze Titan'; second-in-command of the Cuban Liberation Army in the wars of independence against Spain.",
     "story": "Veteran of the Ten Years' War (1868–78). His 1878 'Protest of Baraguá' refused the Zanjón peace because it did not abolish slavery. Led the 1895–96 invasion of western Cuba, marching 1,700 km in 96 days. Killed in action 7 December 1896.",
     "legacy": "National hero of Cuba; his birthday is a major civic observance.",
     "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Philip Foner, 'Antonio Maceo: The Bronze Titan' (1977)"]},

    # ===== MODERN THINKERS =====
    {"id": "bell-hooks", "name": "bell hooks", "category": "intellectuals", "era": "1952–2021", "region": "United States",
     "summary": "American author and cultural critic (Gloria Jean Watkins) whose works including 'Ain't I a Woman?' (1981) and 'Teaching to Transgress' (1994) shaped contemporary feminism and pedagogy.",
     "story": "Took her pen name in lower case from her great-grandmother Bell Blair Hooks, signaling that the substance of ideas matters more than the personality behind them. Taught at Yale, Oberlin, Berea College.",
     "legacy": "Foundational texts of Black feminist theory; her work is taught from secondary schools to PhD programs worldwide.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["bell hooks, 'Ain't I a Woman?' (1981)"]},
    {"id": "stuart-hall", "name": "Stuart Hall", "category": "intellectuals", "era": "1932–2014", "region": "Jamaica / United Kingdom",
     "summary": "Jamaican-British sociologist; founding figure of the Birmingham School of cultural studies and one of the most influential theorists of identity, race, and media of the late 20th century.",
     "story": "Arrived in Britain in 1951 on a Rhodes Scholarship. Co-edited the 'New Left Review' from 1960. As director of the Birmingham Centre for Contemporary Cultural Studies (1968–79), he reshaped academic study of media, race, and class.",
     "legacy": "His essay 'Encoding/Decoding' (1973) is foundational to media studies; his last book 'Familiar Stranger' (2017) is required reading on diaspora.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Stuart Hall, 'Familiar Stranger' (2017, posthumous)"]},
    {"id": "ngugi", "name": "Ngũgĩ wa Thiong'o", "category": "intellectuals", "era": "b. 1938", "region": "Kenya",
     "summary": "Kenyan novelist and theorist; argued in 'Decolonising the Mind' (1986) that African writers should compose in African languages, and switched his own writing from English to Gĩkũyũ.",
     "story": "Detained without trial by the Kenyatta government in 1977 after his Gĩkũyũ-language play 'Ngaahika Ndeenda'. Began writing his prison novel 'Devil on the Cross' on toilet paper.",
     "legacy": "Repeatedly listed as a Nobel-Prize favourite; central to debates on language, decolonization, and literature.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Ngũgĩ wa Thiong'o, 'Decolonising the Mind' (1986)"]},
    {"id": "mbembe", "name": "Achille Mbembe", "category": "intellectuals", "era": "b. 1957", "region": "Cameroon / South Africa",
     "summary": "Cameroonian political philosopher and historian; his concepts of 'necropolitics' (2003) and 'Afropolitanism' reshaped contemporary thought on power, race, and migration.",
     "story": "Educated at the Sorbonne and Johns Hopkins. Long based at WiSER (University of the Witwatersrand). Co-organizes the biennial 'Ateliers de la pensée' in Dakar, a major francophone intellectual gathering.",
     "legacy": "Recipient of the Holberg Prize (2024) — humanities' equivalent of the Nobel.",
     "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Achille Mbembe, 'On the Postcolony' (2001); 'Necropolitics' (2003)"]},
    {"id": "audre-lorde", "name": "Audre Lorde", "category": "intellectuals", "era": "1934–1992", "region": "United States",
     "summary": "Self-described 'Black, lesbian, mother, warrior, poet'; among the most cited voices in feminist, queer, and Black-studies syllabi.",
     "story": "Caribbean-American (St. Croix heritage). Her keynote at the 1979 'Personal and the Political' panel — 'The Master's Tools Will Never Dismantle the Master's House' — became canonical. Residency in Berlin (1984) shaped the Afro-German movement.",
     "legacy": "New York State Poet 1991–93; her essays remain among the most assigned in US humanities classrooms.",
     "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
     "sources": ["Audre Lorde, 'Sister Outsider' (1984)"]},
]


# Mapping figures → civilization_id (from seed_data.py CIVILIZATIONS)
FIGURE_CIVS = {
    "mansa-musa": "mali",
    "sundiata": "mali",
    "shaka": "zulu",
    "taharqa": "kush",
    "amanirenas": "kush",
    "yaa-asantewaa": "asante",
    "amina": "hausa",
    "haile-selassie": "ethiopia",
    "makeda": "ethiopia",
    "hatshepsut": "egypt",
    "cleopatra": "egypt",
    "imhotep": "egypt",
    "nzinga": "kongo",
    "ranavalona": None,  # Madagascar (not yet in civilizations)
}

# Coarse representative year for timeline placement (negative = BCE)
import re

def _representative_year(era: str):
    if not era:
        return None
    s = era.replace("–", "-").replace("—", "-")
    bce = "BCE" in s.upper()
    # Century pattern e.g. "27th c. BCE" or "10th c. BCE"
    m = re.search(r"(\d{1,2})\s*(?:th|st|nd|rd)?\s*c\.", s, re.IGNORECASE)
    if m:
        y = int(m.group(1)) * 100 - 50
        return -y if bce else y
    nums = re.findall(r"(\d{3,4})", s)
    if not nums:
        nums = re.findall(r"(\d{1,4})", s)
    if not nums:
        return None
    y = int(nums[0])
    return -y if bce else y
