"""Mapping figure ids → Wikipedia page titles, used by frontend hook to fetch portrait images."""

FIGURE_WIKIPEDIA = {
    "hatshepsut": "Hatshepsut",
    "cleopatra": "Cleopatra",
    "amanirenas": "Amanirenas",
    "nzinga": "Njinga of Ndongo and Matamba",
    "yaa-asantewaa": "Yaa Asantewaa",
    "amina": "Amina (queen)",
    "makeda": "Queen of Sheba",
    "ranavalona": "Ranavalona I",
    "mansa-musa": "Mansa Musa",
    "sundiata": "Sundiata Keita",
    "shaka": "Shaka",
    "taharqa": "Taharqa",
    "haile-selassie": "Haile Selassie",
    "toussaint": "Toussaint Louverture",
    "dessalines": "Jean-Jacques Dessalines",
    "zumbi": "Zumbi",
    "harriet-tubman": "Harriet Tubman",
    "imhotep": "Imhotep",
    "lewis-latimer": "Lewis Howard Latimer",
    "mark-dean": "Mark Dean (computer scientist)",
    "katherine-johnson": "Katherine Johnson",
    "percy-julian": "Percy Lavon Julian",
    "mlk": "Martin Luther King Jr.",
    "rosa-parks": "Rosa Parks",
    "mandela": "Nelson Mandela",
    "malcolm-x": "Malcolm X",
    "marcus-garvey": "Marcus Garvey",
    "frederick-douglass": "Frederick Douglass",
    "du-bois": "W. E. B. Du Bois",
    "fanon": "Frantz Fanon",
    "achebe": "Chinua Achebe",
    "morrison": "Toni Morrison",
    "louis-armstrong": "Louis Armstrong",
    "fela": "Fela Kuti",
    "miriam-makeba": "Miriam Makeba",
    "muhammad-ali": "Muhammad Ali",
    "jesse-owens": "Jesse Owens",
    "lumumba": "Patrice Lumumba",
    "sankara": "Thomas Sankara",
    "nkrumah": "Kwame Nkrumah",
    "biko": "Steve Biko",
    "angela-davis": "Angela Davis",
    "maya-angelou": "Maya Angelou",
    "wangari": "Wangari Maathai",
    "bob-marley": "Bob Marley",
    "aretha": "Aretha Franklin",
    "garrett-morgan": "Garrett Morgan",
    "alice-ball": "Alice Ball",
    "marie-daly": "Marie Maynard Daly",
    "patricia-bath": "Patricia Bath",
    "mae-jemison": "Mae Jemison",
    "bessie-coleman": "Bessie Coleman",
    "henrietta-lacks": "Henrietta Lacks",
    "senghor": "Léopold Sédar Senghor",
    "cesaire": "Aimé Césaire",
    "damas": "Léon-Gontran Damas",
    "cheikh-anta-diop": "Cheikh Anta Diop",
    "mariama-ba": "Mariama Bâ",
    "sembene": "Ousmane Sembène",
    "boukman": "Dutty Boukman",
    "cecile-fatiman": "Cécile Fatiman",
    "solitude": "Solitude (rebel)",
    "nanny": "Nanny of the Maroons",
    "maceo": "Antonio Maceo Grajales",
    "bell-hooks": "Bell hooks",
    "stuart-hall": "Stuart Hall (cultural theorist)",
    "ngugi": "Ngũgĩ wa Thiong'o",
    "mbembe": "Achille Mbembe",
    "audre-lorde": "Audre Lorde",
}
