import { useMemo, useState } from "react";
import { useI18n } from "../i18n";
import { useTranslated } from "../lib/useTranslated";
import { localizedValue, searchableText } from "../lib/contentSort";

function Text({ value }) { const { lang } = useI18n(); const translated = useTranslated(value || ""); return translated || localizedValue(value, lang) || null; }
function SourceLinks({ ids = [], sourceMap = new Map() }) { const { lang } = useI18n(); if (!ids.length) return null; return <div className="mt-4 flex flex-wrap gap-2">{ids.map((id) => { const source = sourceMap.get(id); if (!source?.url) return null; return <a key={id} href={source.url} target="_blank" rel="noreferrer" className="rounded-full border border-gold/25 px-3 py-1 text-[11px] text-gold/85 hover:bg-gold/10">{localizedValue(source.publisher, lang) || localizedValue(source.title, lang) || id}</a>; })}</div>; }
function datedCollection(container, prefix) { return Object.entries(container || {}).filter(([key, value]) => key.startsWith(`${prefix}_`) && Array.isArray(value)).map(([key, value]) => ({ year:Number(key.slice(prefix.length + 1)) || null, value })).sort((a,b)=>(b.year||0)-(a.year||0))[0] || { year:null, value:[] }; }
function themesFrom(container) { if (!container || Array.isArray(container)) return []; return [...(container.themes || []), ...(container.sections || []), ...(container.items || [])]; }

function ThemeCards({ items, sourceMap }) { if (!items.length) return null; return <section className="grid gap-4 md:grid-cols-2">{items.map((item,index)=><article key={item.id || index} className="rounded-2xl border border-bone/10 bg-bone/[.025] p-5"><h3 className="font-serif text-xl text-bone"><Text value={item.title || item.name} /></h3>{(item.text || item.summary || item.context || item.note) && <p className="mt-3 text-sm leading-7 text-bone/68"><Text value={item.text || item.summary || item.context || item.note} /></p>}<SourceLinks ids={item.sourceIds || item.sources || []} sourceMap={sourceMap} /></article>)}</section>; }
function LanguageItem({ item, notSpecified }) { const percent = item.percent == null ? null : Number(item.percent); return <article className="rounded-xl border border-bone/10 bg-bone/[.025] p-4"><div className="flex items-center justify-between gap-4"><div><h4 className="font-serif text-lg text-bone"><Text value={item.language} /></h4>{item.note && <p className="mt-1 text-xs leading-relaxed text-bone/45"><Text value={item.note} /></p>}</div><strong className="text-gold">{percent == null ? notSpecified : `${percent}%`}</strong></div>{percent != null && <div className="mt-3 h-2 overflow-hidden rounded-full bg-bone/10"><div className="h-full rounded-full bg-gold/70" style={{width:`${Math.min(100,percent)}%`}} /></div>}</article>; }

export function CountryLanguages({ dossier = {}, sourceMap = new Map() }) {
  const { lang } = useI18n();
  const languages = useMemo(() => dossier.languages || {}, [dossier.languages]);
  const official = languages.official || [];
  const householdDataset = useMemo(() => datedCollection(languages,"household"), [languages]);
  const household = householdDataset.value;
  const themes = useMemo(() => themesFrom(languages), [languages]);
  const [query,setQuery] = useState("");
  const labels = lang === "fr" ? {overline:"Langues",title:"Langues officielles, usages et transmission",intro:"Le statut officiel d’une langue ne signifie pas qu’elle est parlée de la même manière dans toutes les régions. Les données et synthèses ci-dessous distinguent statut, usages au foyer et diversité sociale.",official:"Langues officielles",search:"Rechercher une langue",placeholder:"Rechercher une langue…",household:"Langue parlée au foyer",census:householdDataset.year?`Recensement ${householdDataset.year}`:"Données de recensement",notSpecified:"Non indiqué",themes:"Contexte linguistique"} : {overline:"Languages",title:"Official languages, usage and transmission",intro:"Official status does not mean a language is spoken in the same way across every region. The data and syntheses below distinguish legal status, household usage and social diversity.",official:"Official languages",search:"Search for a language",placeholder:"Search for a language…",household:"Language spoken at home",census:householdDataset.year?`${householdDataset.year} census`:"Census data",notSpecified:"Not specified",themes:"Language context"};
  const visible = useMemo(()=>{const needle=searchableText(query);return needle?household.filter(item=>searchableText(item.language,item.note).includes(needle)):household;},[household,query]);
  return <div className="space-y-8"><header className="rounded-2xl border border-gold/20 bg-gradient-to-br from-gold/[.08] to-transparent p-6"><p className="overline text-gold">{labels.overline}</p><h2 className="mt-2 font-serif text-3xl text-bone">{labels.title}</h2><p className="mt-3 max-w-3xl leading-7 text-bone/65">{labels.intro}</p></header>{official.length>0 && <section><p className="overline text-gold">{labels.official}</p><div className="mt-3 flex flex-wrap gap-2">{official.map((value,index)=><span key={`${searchableText(value)}-${index}`} className="rounded-full border border-bone/15 bg-bone/[.025] px-3 py-1.5 text-sm text-bone/75"><Text value={value}/></span>)}</div></section>}{themes.length>0 && <section><h3 className="mb-4 font-serif text-2xl text-bone">{labels.themes}</h3><ThemeCards items={themes} sourceMap={sourceMap}/></section>}{household.length>0 && <><label className="block"><span className="sr-only">{labels.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.placeholder} className="w-full rounded-xl border border-bone/15 bg-bone/[.025] px-4 py-3 text-sm text-bone outline-none placeholder:text-bone/35 focus:border-gold/50" /></label><section className="space-y-3"><div><p className="overline text-gold">{labels.household}</p><h3 className="mt-1 font-serif text-2xl text-bone">{labels.census}</h3></div>{visible.map((item,index)=><LanguageItem key={`${searchableText(item.language)}-${index}`} item={item} notSpecified={labels.notSpecified}/>)}</section></>}{languages.note && <p className="rounded-xl border border-bone/10 bg-black/10 p-4 text-sm leading-6 text-bone/60"><Text value={languages.note}/></p>}<SourceLinks ids={languages.sourceIds || languages.sources || []} sourceMap={sourceMap}/></div>;
}

function ReligionItem({ item, total, locale, label }) { const count=Number(item.count||0); const share=total?(count/total)*100:0; return <article className="rounded-2xl border border-bone/10 bg-bone/[.025] p-5"><h3 className="font-serif text-xl text-bone"><Text value={item.name}/></h3><p className="mt-2 font-serif text-2xl text-gold">{count.toLocaleString(locale)}</p><p className="mt-1 text-xs text-bone/40">{share.toFixed(1)} % {label}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-bone/10"><div className="h-full rounded-full bg-gold/70" style={{width:`${Math.min(100,share)}%`}} /></div>{item.note && <p className="mt-3 text-sm leading-6 text-bone/60"><Text value={item.note}/></p>}</article>; }

export function CountryReligions({ dossier = {}, sourceMap = new Map() }) {
  const { lang }=useI18n();
  const locale=lang==="fr"?"fr-FR":"en-US";
  const religions=useMemo(() => dossier.religions || {}, [dossier.religions]);
  const censusDataset=useMemo(()=>datedCollection(religions,"census"),[religions]);
  const census=censusDataset.value;
  const themes=useMemo(()=>themesFrom(religions),[religions]);
  const [query,setQuery]=useState("");
  const labels=lang==="fr"?{overline:"Religions & convictions",title:"Affiliations, pratiques et pluralité",intro:"Une affiliation déclarée ne décrit pas à elle seule la pratique, les croyances ou les appartenances multiples.",search:"Rechercher une religion ou conviction",placeholder:"Rechercher une religion ou une conviction…",ofTotal:censusDataset.year?`du total affiché · recensement ${censusDataset.year}`:"du total affiché",themes:"Contextes religieux et spirituels"}:{overline:"Religions & beliefs",title:"Affiliations, practices and plurality",intro:"A declared affiliation does not by itself describe practice, belief or multiple forms of belonging.",search:"Search for a religion or belief",placeholder:"Search for a religion or belief…",ofTotal:censusDataset.year?`of displayed total · ${censusDataset.year} census`:"of displayed total",themes:"Religious and spiritual contexts"};
  const visible=useMemo(()=>{const needle=searchableText(query);return needle?census.filter(item=>searchableText(item.name,item.note).includes(needle)):census;},[census,query]);
  const total=census.reduce((sum,item)=>sum+Number(item.count||0),0);
  return <div className="space-y-8"><header className="rounded-2xl border border-gold/20 bg-gradient-to-br from-gold/[.08] to-transparent p-6"><p className="overline text-gold">{labels.overline}</p><h2 className="mt-2 font-serif text-3xl text-bone">{labels.title}</h2><p className="mt-3 max-w-3xl leading-7 text-bone/65">{labels.intro}</p></header>{themes.length>0&&<section><h3 className="mb-4 font-serif text-2xl text-bone">{labels.themes}</h3><ThemeCards items={themes} sourceMap={sourceMap}/></section>}{census.length>0&&<><label className="block"><span className="sr-only">{labels.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.placeholder} className="w-full rounded-xl border border-bone/15 bg-bone/[.025] px-4 py-3 text-sm text-bone outline-none placeholder:text-bone/35 focus:border-gold/50" /></label><div className="grid gap-4 sm:grid-cols-2">{visible.map((item,index)=><ReligionItem key={`${searchableText(item.name)}-${index}`} item={item} total={total} locale={locale} label={labels.ofTotal}/>)}</div></>}{religions.note&&<p className="rounded-xl border border-bone/10 bg-black/10 p-4 text-sm leading-6 text-bone/60"><Text value={religions.note}/></p>}<SourceLinks ids={religions.sourceIds || religions.sources || []} sourceMap={sourceMap}/></div>;
}