#!/usr/bin/env python3
"""Remove all temporary geometric South Africa SVG illustrations and their data references."""

from __future__ import annotations

from pathlib import Path
import re
import shutil
import sys

ROOT = Path.cwd()
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"

if not BACKEND.exists() or not FRONTEND.exists():
    raise SystemExit("Lance ce script depuis la racine du dépôt ~/inonara-app")

TARGET_PATH_RE = re.compile(
    r"/illustrations/south-africa-v(?:17|18|20|21|22|23)/[^'\"\s]+\.svg",
    re.IGNORECASE,
)

TEXT_EXTENSIONS = {".py", ".json", ".js", ".jsx", ".ts", ".tsx", ".md", ".txt"}

# Matches one complete dictionary property, including pprint-wrapped string values.
def property_pattern(key: str, value_pattern: str) -> re.Pattern[str]:
    return re.compile(
        rf"""(?mx)
        ^(?P<indent>[ \t]*)
        (?P<quote>['"]){re.escape(key)}(?P=quote)
        \s*:\s*
        {value_pattern}
        \s*,?
        \n
        """
    )

IMAGE_URL_PROPERTY = property_pattern(
    "image_url",
    r"""(?P<vq>['"])/illustrations/south-africa-v(?:17|18|20|21|22|23)/.*?\.svg(?P=vq)""",
)

# Credits generated by the temporary packs only.
IMAGE_CREDIT_PROPERTY = property_pattern(
    "image_credit",
    r"""(?P<vq>['"])Illustration\s+originale\s+Inonara\b.*?(?P=vq)""",
)

VISUAL_TYPE_PROPERTY = property_pattern(
    "visual_type",
    r"""(?P<vq>['"])illustration(?P=vq)""",
)

def strip_svg_metadata(text: str) -> tuple[str, int]:
    """Remove target image_url plus adjacent generated credit/type from Python-style data."""
    removed = 0

    # Work dict by dict approximately: when a target URL is found, remove the URL,
    # then remove the first generated credit/type before the closing brace.
    while True:
        match = IMAGE_URL_PROPERTY.search(text)
        if not match:
            break

        start, end = match.span()
        text = text[:start] + text[end:]
        removed += 1

        # Limit companion-field cleanup to the current dict.
        closing = text.find("}", start)
        if closing == -1:
            closing = min(len(text), start + 2000)
        segment = text[start:closing]

        credit = IMAGE_CREDIT_PROPERTY.search(segment)
        if credit:
            a, b = credit.span()
            segment = segment[:a] + segment[b:]
            removed += 1

        visual = VISUAL_TYPE_PROPERTY.search(segment)
        if visual:
            a, b = visual.span()
            segment = segment[:a] + segment[b:]
            removed += 1

        text = text[:start] + segment + text[closing:]

    return text, removed

def clean_text_files() -> tuple[int, int]:
    changed_files = 0
    removed_fields = 0

    for base in (BACKEND, FRONTEND / "src"):
        if not base.exists():
            continue

        for path in base.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in TEXT_EXTENSIONS:
                continue

            try:
                original = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue

            if not TARGET_PATH_RE.search(original):
                continue

            cleaned, count = strip_svg_metadata(original)

            # Also remove simple quoted SVG path occurrences from arrays or constants.
            cleaned, loose_count = re.subn(
                r"""(?m)^[ \t]*['"]/illustrations/south-africa-v(?:17|18|20|21|22|23)/[^'"]+\.svg['"],?\s*\n""",
                "",
                cleaned,
            )
            count += loose_count

            if cleaned != original:
                backup = path.with_suffix(path.suffix + ".v24.bak")
                if not backup.exists():
                    shutil.copy2(path, backup)
                path.write_text(cleaned, encoding="utf-8")
                changed_files += 1
                removed_fields += count
                print(f"NETTOYÉ: {path.relative_to(ROOT)}")

    return changed_files, removed_fields

def delete_svg_assets() -> int:
    deleted = 0
    illustrations_root = FRONTEND / "public" / "illustrations"
    if not illustrations_root.exists():
        return 0

    for folder in sorted(illustrations_root.glob("south-africa-v*")):
        if not folder.is_dir():
            continue

        # Delete only SVG assets; preserve any future photographs accidentally stored there.
        for svg in folder.rglob("*.svg"):
            svg.unlink()
            deleted += 1
            print(f"SUPPRIMÉ: {svg.relative_to(ROOT)}")

        # Remove empty directories.
        for child in sorted(folder.rglob("*"), reverse=True):
            if child.is_dir():
                try:
                    child.rmdir()
                except OSError:
                    pass
        try:
            folder.rmdir()
        except OSError:
            pass

    return deleted

def verify() -> list[str]:
    leftovers: list[str] = []

    for base in (BACKEND, FRONTEND / "src"):
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in TEXT_EXTENSIONS:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if TARGET_PATH_RE.search(text):
                leftovers.append(str(path.relative_to(ROOT)))

    illustrations_root = FRONTEND / "public" / "illustrations"
    if illustrations_root.exists():
        for path in illustrations_root.glob("south-africa-v*/**/*.svg"):
            leftovers.append(str(path.relative_to(ROOT)))

    return sorted(set(leftovers))

def main() -> None:
    changed_files, removed_fields = clean_text_files()
    deleted_svgs = delete_svg_assets()
    leftovers = verify()

    print()
    print("BILAN V24")
    print(f"- Fichiers de données nettoyés : {changed_files}")
    print(f"- Champs/références retirés : {removed_fields}")
    print(f"- Fichiers SVG supprimés : {deleted_svgs}")

    if leftovers:
        print("- Références restantes :")
        for item in leftovers:
            print(f"  * {item}")
        raise SystemExit(1)

    print("- Vérification : aucune référence aux SVG temporaires V17–V23.")
    print("OK: nettoyage visuel V24 terminé.")

if __name__ == "__main__":
    main()
