"""Iteration 10 expansion: more civilizations, diaspora, and backfilled place sources."""

EXTRA_CIVILIZATIONS_V3 = [
    {
        "id": "kanem-bornu",
        "name": "Kanem-Bornu Empire",
        "region": "Central Sahel",
        "modern_locations": ["Chad", "Nigeria", "Niger", "Cameroon", "Libya"],
        "coords": [13.45, 14.32],
        "era_start": 700,
        "era_end": 1893,
        "summary": "One of the longest-lived states in African history, spanning twelve centuries on either side of Lake Chad. Adopted Islam in the 11th century and pioneered a sophisticated cavalry-based administration.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Hereditary Mai (king) of the Sayfawa dynasty for ~770 years (one of the longest dynastic reigns in world history); council of officeholders; provincial governors paid in fiefs.",
        "economy_and_trade": "Trans-Saharan trade in slaves, ivory, ostrich feathers, and salt linked to Tripoli and Cairo; controlled the strategic Bilma salt mines.",
        "science_and_knowledge": "Bilingual administration in Kanuri and Arabic; the Mahram (royal land grant) tradition produced documents in continuous use from the 11th century.",
        "art_and_culture": "Quilted cotton armor and chain mail of horse cavalry, Kanuri court poetry, leather and metalwork.",
        "key_figures": [
            {"name": "Mai Dunama Dibalemi", "role": "Reformer king (r. 1210–1248), credited with the empire's first major expansion"},
            {"name": "Mai Idris Alooma", "role": "Reformer who imported Ottoman firearms (r. c. 1571–1603)"},
            {"name": "Rabih az-Zubayr", "role": "Conqueror who ended Bornu independence (r. 1893–1900)"},
        ],
        "timeline": [
            {"year": 1085, "event": "Mai Hummay converts to Islam."},
            {"year": 1380, "event": "Capital moves from Kanem (east of Lake Chad) to Bornu (west)."},
            {"year": 1571, "event": "Idris Alooma's reign begins; firearms transform the army."},
            {"year": 1893, "event": "Rabih az-Zubayr conquers Bornu; French colonial rule follows in 1900."},
        ],
        "sources": ["John Hunwick, 'Sharia in Songhay' (1985)", "Dierk Lange, 'Ancient Kingdoms of West Africa' (2004)"],
    },
    {
        "id": "wolof-empire",
        "name": "Jolof Empire (Wolof)",
        "region": "West Africa",
        "modern_locations": ["Senegal", "The Gambia"],
        "coords": [14.96, -15.10],
        "era_start": 1350,
        "era_end": 1549,
        "summary": "Senegambian federation founded by Ndiadiane Ndiaye uniting the Wolof, Serer, and Tukulor states under the Bourba Jolof, until the 1549 Battle of Danki dissolved it into independent kingdoms.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Confederation of six provinces (Walo, Cayor, Baol, Sine, Saloum, Jolof) under the Bourba Jolof; matrilineal succession through the linger (queen mother) lineage.",
        "economy_and_trade": "Millet, cotton, indigo, gold; the trans-Saharan trade and, from the 1440s, Atlantic coastal trade with Portuguese mariners.",
        "science_and_knowledge": "Wolof oral history (woy poetry, the Ndiadiane Ndiaye foundation myth), advanced cotton weaving, the strict griot/noble/casted craftsperson social system.",
        "art_and_culture": "Pagne textiles, finely worked gold jewelry, mbalax rhythmic foundations, leatherwork.",
        "key_figures": [
            {"name": "Ndiadiane Ndiaye", "role": "Mythical founder (14th c.)"},
            {"name": "Amari Ngoone Sobel Fall", "role": "Damel of Cayor who defeated the Bourba at Danki (1549)"},
        ],
        "timeline": [
            {"year": 1350, "event": "Wolof states confederate under Ndiadiane Ndiaye."},
            {"year": 1455, "event": "Venetian explorer Alvise Cadamosto reports on the empire."},
            {"year": 1549, "event": "Battle of Danki: Cayor secedes; the empire dissolves into independent kingdoms."},
        ],
        "sources": ["Boubacar Barry, 'Senegambia and the Atlantic Slave Trade' (1998)", "Cadamosto, 'Navigationi' (15th c.)"],
    },
    {
        "id": "mutapa",
        "name": "Mutapa Empire",
        "region": "Southern Africa",
        "modern_locations": ["Zimbabwe", "Mozambique"],
        "coords": [-17.10, 31.30],
        "era_start": 1430,
        "era_end": 1760,
        "summary": "Successor to Great Zimbabwe; a Shona kingdom on the Zambezi plateau whose Mwenemutapa rulers controlled gold and ivory trade with the Swahili coast and later the Portuguese.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Sacred kingship of the Mwenemutapa ('Master of the Conquered Lands'); tributary system across the plateau and beyond.",
        "economy_and_trade": "Gold mining (Manica, Matabeleland), ivory, copper, and iron; sustained trade with Sofala and the wider Indian Ocean.",
        "science_and_knowledge": "Stone-walled enclosure (zimbabwe) architecture continued from Great Zimbabwe; sophisticated cattle and gold mining management.",
        "art_and_culture": "Soapstone work, Shona Mhondoro spirit-medium tradition, Mbira music.",
        "key_figures": [
            {"name": "Nyatsimba Mutota", "role": "Founder of the empire after leaving Great Zimbabwe (15th c.)"},
            {"name": "Mavura Mhande Felipe", "role": "King who reluctantly accepted Portuguese vassalage in 1629"},
        ],
        "timeline": [
            {"year": 1450, "event": "Mutota establishes the new state north of Great Zimbabwe."},
            {"year": 1505, "event": "Portuguese establish themselves at Sofala on the coast."},
            {"year": 1629, "event": "Portuguese-imposed treaty makes Mwenemutapa a vassal."},
            {"year": 1760, "event": "Empire fragments into successor states (Rozvi)."},
        ],
        "sources": ["S. I. G. Mudenge, 'A Political History of Munhumutapa' (1988)"],
    },
    {
        "id": "funj",
        "name": "Funj Sultanate (Sennar)",
        "region": "Northeast Africa",
        "modern_locations": ["Sudan", "South Sudan"],
        "coords": [13.55, 33.62],
        "era_start": 1504,
        "era_end": 1821,
        "summary": "Black-African Islamic sultanate ruling the Nile region between Egypt and Ethiopia for over three centuries — a major center of Sufi scholarship and Nilotic trade.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/cd856dce9d4cf5c71b306fa79ba1420d7d918092d25fc78b85217b73ddb7e2bc.png",
        "political_structure": "Sultanate at Sennar; federation of Arabic-Nilotic provinces governed by appointed manjils; influential Sufi tariqas (Qadiriyya, Shadhiliyya) intertwined with state.",
        "economy_and_trade": "Sorghum, sesame, livestock; trade in slaves, gold, and ivory between Egypt, Ethiopia, and the Red Sea.",
        "science_and_knowledge": "Major Islamic scholarly tradition (the 'tabaqat' biographical genre flourished); fusion of Arabic and Nilotic medical and astronomical knowledge.",
        "art_and_culture": "Sufi shrines (qubbas), Funj-style mud-brick architecture, distinctive northern-Sudanese folk music.",
        "key_figures": [
            {"name": "Amara Dunqas", "role": "Founder (r. 1504–1533)"},
            {"name": "Badi II Abu Daqn", "role": "Sultan who centralized the state (r. 1644–1681)"},
        ],
        "timeline": [
            {"year": 1504, "event": "Funj defeat the Christian kingdom of Alodia at the Battle of Soba."},
            {"year": 1727, "event": "Coup of the Hamaj regents reduces the Sultan to a figurehead."},
            {"year": 1821, "event": "Egyptian-Ottoman invasion under Muhammad Ali's son Ismail ends the sultanate."},
        ],
        "sources": ["Jay Spaulding, 'The Heroic Age in Sinnar' (1985)"],
    },
    {
        "id": "mossi",
        "name": "Mossi Kingdoms",
        "region": "West Africa",
        "modern_locations": ["Burkina Faso", "Ghana", "Mali"],
        "coords": [12.36, -1.53],
        "era_start": 1300,
        "era_end": 1896,
        "summary": "Federation of Mossi states (Ouagadougou, Yatenga, Tenkodogo, Fada N'Gourma) on the upper Volta plateau that successfully resisted both Mali and Songhai for centuries.",
        "image_url": "https://static.prod-images.emergentagent.com/jobs/a030947e-7248-4eb4-a138-0bdb852bc956/images/3327733600bbae48c70dda8cc40686aada47907623da33062f2518a29af57ec5.png",
        "political_structure": "Each kingdom ruled by a Mogho Naba (paramount chief); titled offices balanced royal power; non-Islamic cosmology long resisted Sahelian Islamization.",
        "economy_and_trade": "Millet and sorghum agriculture, cattle, cotton; the Mossi cavalry was renowned in the region.",
        "science_and_knowledge": "Strong oral-historical tradition maintained by court griots; Mooré language with a substantial literary tradition since colonization.",
        "art_and_culture": "Mossi masks (karanga, karan-wemba), bronze and brass casting at Bobo-Dioulasso, the elaborate enthronement ceremony of the Mogho Naba (continuing today).",
        "key_figures": [
            {"name": "Naba Oubri", "role": "Founder of the Ouagadougou kingdom (r. 11th c., traditional)"},
            {"name": "Naba Wobgo", "role": "Mogho Naba who resisted the French (r. 1890–1896)"},
        ],
        "timeline": [
            {"year": 1483, "event": "Mossi cavalry raid as far as Walata in present-day Mauritania."},
            {"year": 1497, "event": "Askia Mohammad of Songhai unsuccessfully wars against the Mossi."},
            {"year": 1896, "event": "French forces depose Naba Wobgo; Upper Volta colony established."},
        ],
        "sources": ["Michel Izard, 'Gens du pouvoir, gens de la terre' (1985)"],
    },
]

EXTRA_DIASPORA_V3 = [
    {
        "id": "afro-french", "name": "Afro-French (Hexagone)", "country": "France", "country_iso2": "FR", "status": "documented", "region": "Europe",
        "coords": [48.8566, 2.3522], "era_start": 1500, "era_end": 2025,
        "summary": "France is home to Europe's largest African-descended population, estimated at 3–5 million — a community shaped by overseas departments, postwar labor migration, and a public republican model that officially recognizes no ethnic statistics.",
        "origin_routes": ["Overseas departments (Guadeloupe, Martinique, French Guiana, Réunion, Mayotte)", "West African migration (Senegal, Mali, Côte d'Ivoire, Cameroon, DR Congo)", "Maghreb migration with sub-Saharan heritage"],
        "ethnicities": ["Antillais (Caribbean French)", "Sénégalais, Maliens, Soninké of the Hexagone", "Réunionnais", "Congolese and Cameroonian Parisians"],
        "languages": ["French", "Creole varieties (Antillean, Reunionnais)", "African heritage languages (Wolof, Bambara, Soninké, Lingala)"],
        "religions": ["Catholicism", "Islam (especially among Sahelian and Maghrebi-origin families)", "Pentecostalism"],
        "culture": "Négritude began in 1930s Paris (Senghor, Césaire, Damas); contemporary francophone hip-hop and Afropop (MHD, Aya Nakamura, Booba, Maître Gims, Stromae); the writings of Maryse Condé, Calixthe Beyala, Alain Mabanckou, Léonora Miano.",
        "story": "The 1685 Code Noir governed enslaved life in French colonies until 1848. The 1794 First Republic abolished slavery — reversed by Napoleon in 1802, then re-abolished definitively in 1848. The 1931 Paris Colonial Exposition put millions of Africans on display. On October 17, 1961, French police killed an unknown but substantial number of peaceful pro-independence Algerian demonstrators in Paris, a massacre suppressed from public discussion for decades and only formally acknowledged by the French state in 2012. Post-WWII labor agreements (BUMIDOM 1963) channeled Antilleans to mainland France. The 2005 banlieue uprisings and the 2020 'Adama' protests reshaped national debate.",
        "modern": "Christiane Taubira (Minister of Justice 2012–16, architect of the law recognizing slavery as a crime against humanity, 2001). Aya Nakamura is the most-streamed French-language artist worldwide. The 2023 Black Lives Matter France movement and the Adama Traoré case continue to shape policy.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Pap Ndiaye, 'La condition noire' (2008)", "Sue Peabody, 'There Are No Slaves in France' (1996)", "Jean-Luc Einaudi, 'La Bataille de Paris: 17 octobre 1961' (1991)", "French Presidency, official statement on the 1961 Paris massacre (2012)"],
    },
    {
        "id": "afro-mexican-texan", "name": "Black Seminoles (Mascogos / Afro-Texan)", "country": "Mexico & United States", "scope": "regional", "status": "documented",
        "region": "North America", "coords": [29.32, -100.42],  # Nacimiento de los Negros, Coahuila
        "era_start": 1690, "era_end": 2025,
        "summary": "A maroon community formed in colonial Florida from Africans who joined the Seminole nation; expelled to Oklahoma in 1838, splintered to Mexico in 1850 under John Horse, and recruited as US Army scouts after 1870.",
        "origin_routes": ["Spanish Florida (1690s — fled British plantations to Spanish protection)", "Indian Territory / Oklahoma (after the Second Seminole War 1842)", "Coahuila, Mexico (after 1850 — invited by President Mariano Arista to settle frontier lands)", "Eagle Pass, Texas (as US Seminole Negro Indian Scouts from 1870)"],
        "ethnicities": ["Mascogos (Spanish-speaking community in Coahuila)", "Seminole Negro Indian Scouts (Texas)", "Black Seminoles of Oklahoma (Brackettville and Wewoka)"],
        "languages": ["Afro-Seminole Creole (English-based, on the verge of extinction)", "Mexican Spanish (Mascogos)", "Seminole Mvskoke heritage"],
        "religions": ["Black Baptist church traditions", "Catholic adaptations among Mexican Mascogos"],
        "culture": "Distinctive 'shouting' ring-shouts at Juneteenth-style gatherings, capeyuye songs, the Mascogo Day celebrations every 19 October in Coahuila.",
        "story": "Africans began fleeing British Carolina to Spanish Florida in the 1690s; the Spanish formally promised freedom in 1733 if they converted to Catholicism. After the Second Seminole War (1835–1842), the Trail of Tears brought roughly 500 Black Seminoles to Oklahoma. In 1850, Chief Coacoochee (Wild Cat) and the Seminole interpreter John Horse led a band southward across the Rio Grande, settling at Nacimiento. Four Seminole Negro Indian Scouts earned the Medal of Honor in the 1870s — including John Ward and Pompey Factor.",
        "modern": "Both the Mascogos of Coahuila and the descendants in Brackettville/Wewoka have organized to preserve language and identity; the Seminole Indian Scouts Cemetery near Eagle Pass remains a pilgrimage site.",
        "image_url": "https://images.unsplash.com/photo-1605007493699-af75e7d68bb3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Kenneth Porter, 'The Black Seminoles' (1996, posthumous)", "Kevin Mulroy, 'Freedom on the Border' (1993)"],
    },
    {
        "id": "afro-filipino", "name": "Afro-Filipino", "country": "Philippines", "country_iso2": "PH", "status": "documented", "region": "Southeast Asia",
        "coords": [14.0833, 122.9333],  # Camarines Norte / Aeta heartland
        "era_start": 1565, "era_end": 2025,
        "summary": "A complex three-way fusion: indigenous Aeta/Negrito peoples (whose ancestors reached the Philippines 30,000+ years ago), Africans brought via the Manila-Acapulco galleon trade, and contemporary African migration to Manila and Cebu.",
        "origin_routes": ["Indigenous Negrito populations (Aeta, Agta, Ati, Batak — deep prehistoric ancestry)", "Africans arriving via the Manila Galleon (1565–1815) — sailors, soldiers, enslaved labor brought from Mozambique, Madagascar, and Latin American slave ports", "African American servicemen during US colonial period (1898–1946) and the Subic/Clark base era (1946–1992)", "Recent African student and professional migration to Manila"],
        "ethnicities": ["Aeta and Agta indigenous communities (~150,000)", "Mestizo communities tracing partial galleon-era African heritage", "Anak ng GI: children of African-American servicemen and Filipina mothers"],
        "languages": ["Filipino (Tagalog)", "Cebuano", "regional Aeta languages (Sinauna, Mag-anchi)", "English"],
        "religions": ["Catholicism", "Iglesia ni Cristo", "Indigenous Aeta animism in some communities", "Islam (Muslim Filipinos in Mindanao with deep cross-Indian-Ocean ties)"],
        "culture": "Aeta dance and forager music (still practiced in Pampanga and Zambales), the Filipino genre of soul- and R&B-inflected music (Apo Hiking Society, the Rico Blanco generation), and a small but visible Afro-Filipino acting and modeling presence (Asia Agcaoili, Rio Diaz).",
        "story": "The Spanish Manila Galleon trade (1565–1815) linked Acapulco to Manila across the Pacific in annual voyages. Africans brought from Latin American ports and Mozambique appear in colonial Manila parish records under designations like 'negro' and 'cafre'. After Mount Pinatubo erupted in 1991 it displaced tens of thousands of Aeta. The 1898 Spanish-American War handed the Philippines to the United States and a generation of African American 'Buffalo Soldiers' served — many refused to fight Filipinos and some, like David Fagen, defected.",
        "modern": "The Philippines does not officially count Afro-Filipinos; the Aeta are recognized as one of the country's Indigenous Peoples. Asia Pop Comicon and indie media have begun documenting the Afro-Filipino experience.",
        "image_url": "https://images.unsplash.com/photo-1770750738052-6a7bd508ddab?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
        "sources": ["Eric Anderson Reyes, 'The Black Galleon' (2018 art-history thesis)", "Jean-Paul Rodrigue Rallu, 'Histoire des Philippines' (2000)"],
    },
]

# Sources to backfill into the older PLACES entries from seed_extended.py
PLACE_SOURCES_BACKFILL = {
    "lalibela": ["UNESCO World Heritage (Rock-Hewn Churches of Lalibela)", "David Phillipson, 'Ancient Churches of Ethiopia' (2009)"],
    "timbuktu": ["UNESCO World Heritage (Timbuktu)", "Shamil Jeppie & Souleymane Bachir Diagne (eds.), 'The Meanings of Timbuktu' (2008)"],
    "djenne": ["UNESCO World Heritage (Old Towns of Djenné)", "Charlotte Joy, 'The Politics of Heritage Management in Mali' (2012)"],
    "lake-turkana": ["UNESCO World Heritage (Lake Turkana National Parks)", "Meave Leakey et al., Nature 2012 (Koobi Fora hominids)"],
    "olduvai": ["Mary Leakey, 'Olduvai Gorge' (1971)", "UNESCO World Heritage (Ngorongoro Conservation Area)"],
    "lalibela2": ["UNESCO World Heritage (Ruins of Kilwa Kisiwani)", "Neville Chittick, 'Kilwa: An Islamic Trading City on the East African Coast' (1974)"],
    "elmina": ["UNESCO World Heritage (Forts and Castles, Volta, Greater Accra, Central and Western Regions)", "Albert van Dantzig, 'Forts and Castles of Ghana' (1980)"],
    "goree": ["UNESCO World Heritage (Island of Gorée)", "Ana Lucia Araujo, 'Public Memory of Slavery' (2010)"],
    "palmares": ["Décio Freitas, 'Palmares: a guerra dos escravos' (1973)", "Stuart Schwartz, 'Slaves, Peasants, and Rebels' (1992)"],
    "harlem": ["David Levering Lewis, 'When Harlem Was in Vogue' (1981)", "Jonathan Gill, 'Harlem: The Four Hundred Year History' (2011)"],
    "salvador": ["UNESCO World Heritage (Historic Centre of Salvador de Bahia)", "Kim Butler, 'Freedoms Given, Freedoms Won' (1998)"],
    "zanzibar": ["UNESCO World Heritage (Stone Town of Zanzibar)", "Abdul Sheriff, 'Slaves, Spices and Ivory in Zanzibar' (1987)"],
}
